<?php $this->data->sidebar->each('body', function ($sidebar) { ?>    
    <?php if ( $sidebar->get('options.template.root') ) : ?>
        <?php require $sidebar->get('options.template.root'); return; ?>
    <?php endif; ?>
    <div class="list list-small list-name-<?= $sidebar->getCurrentPositionName() ?>">
        <?php if ( $sidebar->get('options.template.body') ) : ?>
            <?php require $sidebar->get('options.template.body'); ?>
        <?php else : ?>
            <?php if ( $sidebar->get('data.title') ) : ?>
                <div class="list-head">
                    <span><?= $sidebar->get('data.title') ?></span>
                </div>
            <?php endif; ?>
            <div class="list-body">
                <?php if ( $sidebar->get('body') ) : ?>
                    <?php $sidebar->each('body', function ($sidebar) { ?>
                        <?php if ( $sidebar->get('options.template.root') ) : ?>
                            <?php require $sidebar->get('options.template.root'); return; ?>
                        <?php endif; ?>
                        <div class="list-row<?php if ( $sidebar->get('options.selected') ) : ?> list-row-selected<?php endif; ?><?php if ( $sidebar->get('options.disabled') ) : ?> list-row-disabled<?php endif; ?> list-row-name-<?= $sidebar->getCurrentPositionName() ?> list-row-type-<?= $sidebar->get('options.type') ?>" js="list-row">
                            <?php if ( $sidebar->get('options.template.body') ) : ?>
                                <?php require $sidebar->get('options.template.body'); ?>
                            <?php else : ?>

                                <?php if ( $sidebar->get('options.type') === 'button' ) : ?>
                                    <a href="<?php if ( $sidebar->get('data.href') ) : ?><?= $sidebar->get('data.href') ?><?php endif; ?>"><i class="<?= $sidebar->get('data.icon') ?>"></i> <?= $sidebar->get('data.title') ?></a>
                                <?php endif; ?>

                                <?php if ( $sidebar->get('options.type') === 'link' ) : ?>
                                    <div class="table">
                                        <div class="table-left"><?= $sidebar->get('data.title') ?>:</div>
                                        <div class="table-right">
                                            <a class="button" href="<?= $sidebar->get('data.href') ?>"><?php if ($sidebar->get('data.icon')) : ?><i class="<?= $sidebar->get('data.icon') ?>"></i> <?php endif; ?><?= $sidebar->get('data.button') ?></a>
                                        </div>
                                    </div>
                                <?php endif; ?>

                                <?php if ( $sidebar->get('options.type') === 'table' ) : ?>
                                    <?php $sidebar->each('body', function ($sidebar) { ?>
                                        <div class="table">
                                            <div class="table-left"><?= $sidebar->get('data.title') ?>:</div>
                                            <div class="table-right">
                                                <?php if ( $sidebar->get('options.template.body') ) : ?>
                                                    <?php require $sidebar->get('options.template.body'); ?>
                                                <?php else : ?>
                                                    <?= $sidebar->get('data.value') ?>
                                                <?php endif; ?>
                                            </div>
                                        </div>
                                    <?php }); ?>
                                <?php endif; ?>

                                <?php if ( $sidebar->get('options.type') === 'list' ) : ?>
                                    <?php if ( $sidebar->get('body') ) : ?>
                                        <?php $sidebar->each('body', function ($sidebar) { ?>
                                            <?php require $sidebar->get('options.template.body'); ?>
                                        <?php }); ?>
                                    <?php else : ?>
                                        <?php if ( $sidebar->get('data.empty') ) : ?>
                                            <?= $sidebar->get('data.empty') ?>
                                        <?php endif; ?>
                                    <?php endif; ?>

                                <?php endif; ?>
                            <?php endif; ?>
                        </div>
                    <?php }); ?>
                <?php else : ?>
                    <?php if ( $sidebar->get('data.empty') ) : ?>
                        <div class="list-row">
                            <?= $sidebar->get('data.empty') ?>
                        </div>
                    <?php endif; ?>
                <?php endif; ?>
            </div>
        <?php endif; ?>
    </div>
<?php }); ?>