<!DOCTYPE html>
<html id="html" lang="cs-cz" class="html-hidden">

    <?php require $path->build('Root/Style:/Templates/Blocks/Head.phtml'); ?>

    <body id="body">
        
        <?php require $path->build('Root/Style:/Templates/Blocks/Visualization/Navbar/Navbar.phtml'); ?>

        <div class="page" js="page">
            <?php require $path->build('Root/Style:/Templates/Blocks/NavbarTop.phtml'); ?>
            <div class="page-body">
                <div class="page-container container">
            
                    <?php if ($this->data->get('data.message.text')) : ?>
                        <div class="alert alert-type-<?= $this->data->get('data.message.type') ?>" js="alert">
                            <div class="alert-icon">
                                    <?php if ($this->data->get('data.message.type') == 'success') : ?>
                                        <i class="fa-solid fa-check"></i>
                                    <?php else : ?>
                                        <i class="fa-solid fa-exclamation"></i>
                                    <?php endif; ?>
                                </div>      
                            <div class="alert-body">
                                <div class="alert-content">
                                    <?= $this->data->get('data.message.text') ?>
                                </div>
                                <span ajax="close" class="alert-close">
                                    <i class="fa-solid fa-xmark"></i>
                                </span>
                            </div>
                        </div>
                    <?php endif; ?>
                    <?php require $path->build('Root/Style:/Templates/Blocks/Visualization/Block/Block.phtml'); ?>
                    <?php $this->data->notification->each('body', function ($notifi) { ?>
                        <div class="alert alert-type-<?= $notifi->get('data.type') ?> alert-name-<?= $notifi->get('data.name') ?>">
                            <div class="alert-icon">
                                <?php if ($notifi->get('data.icon')) : ?>
                                    <i class="<?= $notifi->get('data.icon') ?>"></i>
                                <?php else : ?>
                                    <?php if ($notifi->get('data.type') == 'info') : ?>
                                        <i class="fa-solid fa-circle-info"></i>
                                    <?php elseif ($notifi->get('data.type') == 'notice') : ?>
                                        <i class="fa-solid fa-bell"></i>
                                    <?php else : ?>
                                        <i class="fa-solid fa-exclamation-triangle"></i>
                                    <?php endif; ?>
                                <?php endif; ?>
                            </div>        
                            <div class="alert-body">
                                <div class="alert-content<?php if (!$notifi->get('data.text')) : ?> alert-content-center<?php endif; ?>">
                                    <span class="alert-title"><?= $notifi->get('data.title') ?></span>
                                    <?php if ($notifi->get('data.text')) : ?>
                                        <br>
                                        <span><?= $notifi->get('data.text') ?></span>
                                    <?php endif; ?>
                                </div>
                                <?php if ($notifi->get('data.button')) : ?>
                                    <div class="alert-buttons">
                                        <?php $notifi->each('data.button', function ($button) { ?>
                                            <a class="alert-button" href="<?= $button->get('href') ?>"><i class="<?= $button->get('icon') ?>"></i> <?= $button->get('text') ?></a>
                                        <?php }); ?>
                                    </div>
                                <?php endif; ?>
                            </div>
                        </div>
                    <?php }); ?>
                    <?= $this->show(); ?>
                </div>
            </div>
        </div>
        <div class="title" js="title"><span class="text" js="text"></span><div class="title-arrow"><span js="title-arrow"></span></div></div>
        <div class="window" js="window">
            <div class="window-content">
                <div class="window-head" js="window-title"></div>
                <div class="window-body" js="window-body"></div>
                <div class="window-bottom" js="window-bottom">
                    <a class="button button-confirm" ajax="confirm" js="window-submit"></a>
                    <a class="button" ajax="window-close" js="window-cancel"></a>
                </div>
            </div>
        </div>
        <div class="opacity" js="opacity"></div>
        <div class="window window-alert" js="window-alert">
            <div class="window-content">
                <div class="window-icon">
                    <i class="fa-solid fa-exclamation" js="window-alert-icon-error"></i>
                    <i class="fa-solid fa-check" js="window-alert-icon-success"></i>
                </div>
                <div class="window-body" js="window-alert-body"></div>
            </div>
        </div>
        <script src="/Assets/jQuery/jQuery.min.js?<?= $system->get('session.scripts') ?>"></script>
        <script src="/Assets/cAjax/cAjax.min.js?<?= $system->get('session.scripts') ?>"></script>
        <script src="/Includes/Admin/Styles/Default/Themes/Addons.min.js?<?= $system->get('session.scripts') ?>"></script>
        <?php if ( $this->data->get('data.page') == 'App\Page\Index' ) : ?>
            <script src="/Assets/ApexCharts/ApexCharts.min.js?<?= $system->get('session.scripts') ?>"></script>
        <?php endif; ?>
        <?php if ( $this->data->get('options.editor') ) : ?>
            <script src="/Assets/Trumbowyg/trumbowyg.min.js?<?= $system->get('session.scripts') ?>"></script>
            <?php if ($this->system->get('site.language_editor') != 'en') : ?>
                <script src="/Assets/Trumbowyg/langs/<?= $system->get('site.language_editor') ?>.min.js?<?= $system->get('session.scripts') ?>"></script>
            <?php endif; ?>
            <script src="/Assets/Trumbowyg/plugins/emoji/trumbowyg.emoji.min.js?<?= $system->get('session.scripts') ?>"></script>
            <script src="/Assets/Trumbowyg/plugins/upload/trumbowyg.upload.min.js?<?= $system->get('session.scripts') ?>"></script>
            <script src="/Assets/Trumbowyg/plugins/noembed/trumbowyg.noembed.min.js?<?= $system->get('session.scripts') ?>"></script>
            <script src="/Assets/Trumbowyg/plugins/preformatted/trumbowyg.preformatted.min.js?<?= $system->get('session.scripts') ?>"></script>
            <script>$('[trumbowyg="big"]').trumbowyg(<?= json_encode($this->data->get('data.trumbowyg.big')) ?>);</script>
        <?php endif; ?>
        <?php if ( $this->data->get('options.photoSwipe') ) : ?>
        <script type="module">
            import PhotoSwipeLightbox from '/Assets/PhotoSwipe/dist/photoswipe-lightbox.esm.js';
            const lightbox = new PhotoSwipeLightbox({
                gallery: '.pswp-images',
                children: 'a.image',
                pswpModule: () => import('/Assets/PhotoSwipe/dist/photoswipe.esm.js')
            });
            lightbox.on('uiRegister', function() {
                lightbox.pswp.ui.registerElement({
                    name: 'custom-caption',
                    order: 9,
                    isButton: false,
                    appendTo: 'root',
                    html: 'Caption text',
                    onInit: (el, pswp) => {
                    lightbox.pswp.on('change', () => {
                        const currSlideElement = lightbox.pswp.currSlide.data.element;
                        let captionHTML = '';
                        if (currSlideElement) {
                        const hiddenCaption = currSlideElement.querySelector('.hidden-caption-content');
                        if (hiddenCaption) {
                            // get caption from element with class hidden-caption-content
                            captionHTML = hiddenCaption.innerHTML;
                        } else {
                            // get caption from alt attribute
                            captionHTML = currSlideElement.querySelector('img').getAttribute('alt');
                        }
                        }
                        el.innerHTML = captionHTML || '';
                    });
                    }
                });
            });
            lightbox.init();
        </script>
    <?php endif; ?>
    </body>
    
</html>