<!DOCTYPE html>
<html id="html" lang="cs-cz" class="html-hidden">

    <?php require $this->template->template('/Blocks/Head.phtml'); ?>

    <body id="body">
        
        <?php require $this->template->template('/Blocks/Visualization/Navbar/Navbar.phtml'); ?>

        <div class="page" ajax-selector="page">
            <?php require $this->template->template('/Blocks/NavbarTop.phtml'); ?>
            <div class="page-body">
                <div class="page-container container">
            
                    <?php if (!empty($this->data->data['message']['text'])) : ?>
                        <div class="page-alert page-alert-type-<?= $this->data->data['message']['type'] ?>" ajax-selector="alert">
                            <div class="page-alert-icon">
                                    <?php if ($this->data->data['message']['type'] == 'success') : ?>
                                        <i class="fas fa-check"></i>
                                    <?php else : ?>
                                        <i class="fas fa-exclamation"></i>
                                    <?php endif; ?>
                                </div>      
                            <div class="page-alert-body">
                                <div class="page-alert-content">
                                    <?= $this->data->data['message']['text'] ?>
                                </div>
                                <span ajax="close" class="page-alert-close">
                                    <i class="fas fa-times"></i>
                                </span>
                            </div>
                        </div>
                    <?php endif; ?>
                    <?= $this->show(); ?>
                </div>
            </div>
        </div>
        <div class="title" ajax-selector="title"><span class="text" ajax-selector="text"></span><div class="arrow"></div></div>
        <div class="window" ajax-selector="window">
            <div class="window-content">
                <div class="window-head" ajax-selector="window-title"></div>
                <div class="window-body" ajax-selector="window-body"></div>
                <div class="window-bottom" ajax-selector="window-bottom">
                    <a class="button button-confirm" ajax="confirm" ajax-selector="window-submit"></a>
                    <a class="button" ajax="window-close" ajax-selector="window-cancel"></a>
                </div>
            </div>
        </div>
        <div class="window-opacity"></div>
        <div class="window window-alert" ajax-selector="window-alert">
            <div class="window-content">
                <div class="window-body" ajax-selector="window-alert-body"></div>
            </div>
        </div>
        <script src="/Assets/jQuery/jQuery.min.js??<?= $this->system->get('session.scripts') ?>"></script> 
        <script src="/Assets/cAjax/cAjax.min.js?<?= $this->system->get('session.scripts') ?>"></script>
        <script src="/Includes/Admin/Styles/Default/Themes/Addons.min.js?<?= $this->system->get('session.scripts') ?>"></script>
        <script src="/Assets/ApexCharts/ApexCharts.min.js?<?= $this->system->get('session.scripts') ?>"></script>
    </body>
    
</html>