<!DOCTYPE html>
<html id="html" lang="cs-cz" class="html-full html-hidden">

    <head>
        <?php require $path->build('Root/Style:/Templates/Blocks/Head.phtml'); ?>
    </head>

    <body>

        <div class="page">
            <div class="page-column page-column-big">
                <div class="page-column-icon">
                    <i class="fa-solid fa-exclamation"></i>
                </div>
                <div class="page-column-title"><?= $language->get('L_ERROR') ?></div>
                <div class="page-column-description"><?= $language->get('L_ERROR_DESC') ?><br><br>
                    <a href="/"><i class="fa-solid fa-chevron-left"></i> <?= $language->get('L_BACK') ?></a>
                </div>
            </div>
        </div>
        <?php require $path->build('Root/Style:/Templates/Blocks/Cookie.phtml'); ?>
        <?php require ROOT . '/Includes/Template/Footer.phtml' ?>
    </body>
    
</html>