<div class="page-layout">
    <?php if ( $this->system->get('site.mode') == 'forum' ) : ?>
        <div class="chart">
            <div class="chart-head"><?= $language->get('L_STATISTIC.L_TOPIC_POST.L_MONTH') ?></div>
            <div class="chart-body">
                <div id="forum" style="height:300px;"></div>
            </div>
        </div>
    <?php endif; ?>
    <?php require $path->build('Root/Style:/Templates/Blocks/Visualization/Lists/Lists.phtml'); ?>
    <?php if ( $this->system->get('site.mode') == 'forum' ) : ?>
        <div class="chart">
            <div class="chart-head"><?= $language->get('L_STATISTIC.L_USER.L_MONTH') ?></div>
            <div class="chart-body">
                <div id="users" style="height:300px;"></div>
            </div>
        </div>
        <?php require $path->build('Root/Style:/Templates/Blocks/Visualization/Lists/Lists.phtml'); ?>
    <?php endif; ?>
    <?php if ($this->user->perm->has('admin.log')) : ?>
        <?php require $path->build('Root/Style:/Templates/Blocks/Visualization/Lists/Lists.phtml'); ?>
    <?php endif; ?>
    <?php require $path->build('Root/Style:/Templates/Blocks/Visualization/Form/Form.phtml'); ?>
</div>
<script src="/Assets/ApexCharts/ApexCharts.min.js"></script>
<script>

    var data = JSON.parse(JSON.stringify(<?= $this->data->chart ?>));

    var chart = new ApexCharts(document.querySelector("#forum"), {
        colors:['#3174d7', '#4CAF50'],
        legend: {show: false},
        chart: {
            height: '100%',
            type: 'area',
            toolbar: {
                show: false
            }
        },
        dataLabels: {
            enabled: false
        },
        stroke: {
          curve: 'straight'
        },
        series: [
            {
                name: '<?= $language->get('L_POSTS') ?>',
                data: data.posts
            },
            {
                name: '<?= $language->get('L_TOPICS') ?>',
                data: data.topics
            }
        ],
        xaxis: {
            categories: data.date
        }
    });
    chart.render();

    var chart = new ApexCharts(document.querySelector("#users"), {
        colors:['#e68900'],
        chart: {
            height: '100%',
            type: 'area',
            toolbar: {
                show: false
            }
        },
        dataLabels: {
            enabled: false
        },
        stroke: {
          curve: 'straight'
        },
        series: [
            {
                name: '<?= $language->get('L_USERS') ?>',
                data: data.users
            }
        ],
        xaxis: {
            categories: data.date
        }
    });
    
    chart.render();
</script>