<?php require $this->template->template('/Blocks/Visualization/Block/Block.phtml'); ?>
<?php require $this->template->template('/Blocks/Visualization/Field/Field.phtml'); ?>
<?php require $this->template->template('/Blocks/Visualization/Lists/Lists.phtml'); ?>

<?php if (isset($this->data->pagination)) : ?>
    <?php if ($this->data->pagination['enabled'] ?? false === true) : ?>
        <?php require $this->template->template('/Blocks/Pagination.phtml'); ?>
    <?php endif; ?>
<?php endif; ?>