<div class="page-layout">
    <div class="chart">
        <div class="chart-head"><?= $language->get('L_STATISTIC.L_USER.L_MONTH') ?></div>
        <div class="chart-body">
            <div id="userDay" style="height:300px;"></div>
        </div>
    </div>

    <div class="chart">
        <div class="chart-head"><?= $language->get('L_STATISTIC.L_USER.L_YEAR') ?></div>
        <div class="chart-body">
            <div id="userMonth" style="height:300px;"></div>
        </div>
    </div>
</div>

<?php require $path->build('Root/Style:/Templates/Blocks/Visualization/Block/Block.phtml'); ?>

<div class="page-layout">
    <div class="chart">
        <div class="chart-head"><?= $language->get('L_STATISTIC.L_TOPIC.L_MONTH') ?></div>
        <div class="chart-body">
            <div id="topicDay" style="height:300px;"></div>
        </div>
    </div>
    
    <div class="chart">
        <div class="chart-head"><?= $language->get('L_STATISTIC.L_TOPIC.L_YEAR') ?></div>
        <div class="chart-body">
            <div id="topicMonth" style="height:300px;"></div>
        </div>
    </div>
</div>

<?php require $path->build('Root/Style:/Templates/Blocks/Visualization/Block/Block.phtml'); ?>

<div class="page-layout">
    <div class="chart">
        <div class="chart-head"><?= $language->get('L_STATISTIC.L_POST.L_MONTH') ?></div>
        <div class="chart-body">
            <div id="postDay" style="height:300px;"></div>
        </div>
    </div>
    
    <div class="chart">
        <div class="chart-head"><?= $language->get('L_STATISTIC.L_POST.L_YEAR') ?></div>
        <div class="chart-body">
            <div id="postMonth" style="height:300px;"></div>
        </div>
    </div>
</div>

<script src="/Assets/ApexCharts/ApexCharts.min.js"></script>
<script>

    var data = JSON.parse(JSON.stringify(<?= $this->data->chart ?>));
    console.log(data);
    var chart = new ApexCharts(document.querySelector("#userDay"), {
        colors:['#3174d7'],
        chart: {
            height: '100%',
            type: 'area',
            toolbar: {show: false}
        },
        dataLabels: {enabled: false},
        stroke: {
          curve: 'straight'
        },
        series: [{
                name: '<?= $language->get('L_USERS') ?>',
                data: data.day.users
            }
        ],
        xaxis: {
            categories: data.day.date
        }
    });
    chart.render();

    var chart = new ApexCharts(document.querySelector("#userMonth"), {
        colors:['#3174d7'],
        chart: {
            height: '100%',
            type: 'area',
            toolbar: {show: false}
        },
        dataLabels: {enabled: false},
        stroke: {
          curve: 'straight'
        },
        series: [{
                name: '<?= $language->get('L_USERS') ?>',
                data: data.month.users
            }
        ],
        xaxis: {
            categories: data.month.date
        }
    });
    chart.render();

    var chart = new ApexCharts(document.querySelector("#topicDay"), {
        colors:['#e68900'],
        chart: {
            height: '100%',
            type: 'area',
            toolbar: {show: false}
        },
        dataLabels: {enabled: false},
        stroke: {
          curve: 'straight'
        },
        series: [{
                name: '<?= $language->get('L_TOPICS') ?>',
                data: data.day.topics
            }
        ],
        xaxis: {
            categories: data.day.date
        }
    });
    chart.render();

    var chart = new ApexCharts(document.querySelector("#topicMonth"), {
        colors:['#e68900'],
        chart: {
            height: '100%',
            type: 'area',
            toolbar: {show: false}
        },
        dataLabels: {enabled: false},
        stroke: {
          curve: 'straight'
        },
        series: [{
                name: '<?= $language->get('L_TOPICS') ?>',
                data: data.month.topics
            }
        ],
        xaxis: {
            categories: data.month.date
        }
    });
    chart.render();

    var chart = new ApexCharts(document.querySelector("#postDay"), {
        colors:['#de4b4b'],
        chart: {
            height: '100%',
            type: 'area',
            toolbar: {show: false}
        },
        dataLabels: {enabled: false},
        stroke: {
          curve: 'straight'
        },
        series: [{
                name: '<?= $language->get('L_POSTS') ?>',
                data: data.day.posts
            }
        ],
        xaxis: {
            categories: data.day.date
        }
    });
    chart.render();

    var chart = new ApexCharts(document.querySelector("#postMonth"), {
        colors:['#de4b4b'],
        chart: {
            height: '100%',
            width: '100%',
            type: 'area',
            toolbar: {show: false}
        },
        dataLabels: {enabled: false},
        stroke: {
          curve: 'straight'
        },
        series: [{
                name: '<?= $language->get('L_POSTS') ?>',
                data: data.month.posts
            }
        ],
        xaxis: {
            categories: data.month.date
        }
    });
    chart.render();
</script>