<?php if (!$this->data->form->get('body.update.body.available')) : ?>
    <div class="list list-name-page" js="list">
        <div class="list-body" js="list-body">
            <div class="list-row">
                <div class="list-row-inner" js="list-row-inner">
                    <div class="list-row-body">
                        <div class="list-row-big">
                            <span class="list-title"><?= $this->language->get('L_UPDATE.L_NO') ?></span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
<?php endif; ?>
<?php require $path->build('Root/Style:/Templates/Blocks/Visualization/Form/Form.phtml'); ?>

<?php if (isset($this->data->pagination)) : ?>
    <?php if ($this->data->pagination['enabled'] ?? false === true) : ?>
        <?php require $path->build('Root/Style:/Templates/Blocks/Pagination.phtml'); ?>
    <?php endif; ?>
<?php endif; ?>