<?php require $this->template->template('/Blocks/Visualization/Block/Block.phtml'); ?>
<div class="page-alert">
    <div class="page-alert-icon">
        <i class="fas fa-exclamation"></i>
    </div>
    <div class="page-alert-body">
        <div class="page-alert-content">
            <span><?= $L_UPDATE_WARNING_PLUGINS ?></span>
        </div>
    </div>
</div>
<?php require $this->template->template('/Blocks/Visualization/Field/Field.phtml'); ?>

<?php if (isset($this->data->pagination)) : ?>
    <?php if ($this->data->pagination['enabled'] ?? false === true) : ?>
        <?php require $this->template->template('/Blocks/Pagination.phtml'); ?>
    <?php endif; ?>
<?php endif; ?>