<div class="navbar navbar-top" js="navbar navbar-top">
    <div class="navbar-content">
        <div class="navbar-button">
            <a href="<?= INDEX ?>">
                <i class="fa-solid fa-angle-left"></i>
                <span><?= $language->get('L_NAVBAR.L_BACK') ?></span>
            </a>
        </div>
        <div class="navbar-button navbar-button-collapse">
            <a ajax="collapse-navbar">
                <i class="fa-solid fa-bars"></i></span>
            </a>
        </div>
        <div class="loading" js="loading">
            <div></div>
            <div></div>
            <div></div>
            <div></div>
        </div>
    </div>
    <div class="breadcrumb">
        <?php $i = 1; $this->data->breadcrumb->each('body', function ($breadcrumb) use (&$i, $url) { ?>
            <a href="<?= $url->build($breadcrumb->get('data.href')) ?>"><?= $breadcrumb->get('data.title') ?></a> <?php if ( count($this->data->breadcrumb->get('body')) != $i) : ?>><?php endif; ?>
        <?php $i++; }); ?>
    </div>
</div>