<?php $this->data->list->each('body', function ($list) { ?>
    <div class="list list-name-<?= $list->get('data.html.name') ?: $list->getCurrentPositionName() ?>">
        <?php if ( $list->get('data.title') ) : ?>
            <div class="list-head">
                <div class="list-row-big">
                    <span><?= $list->get('data.title') ?></span>
                    <?php if ($list->get('data.desc') ) : ?>
                        <br>
                        <span><?= $list->get('data.desc') ?></span>
                    <?php endif; ?>
                </div>
                <?php if ($list->get('data.small.title')) : ?>
                    <div class="list-row-small">
                        <?= $list->get('data.small.title') ?>
                    </div>
                <?php endif; ?>
                <?php if ( $list->get('data.medium.title') ) : ?>
                    <div class="list-row-medium">
                        <?= $list->get('data.medium.title') ?>
                    </div>
                <?php endif; ?>
            </div>
        <?php endif; ?>
        <?php if ( $list->get('body') ) : ?>
            <div class="list-body">
                <?php $list->each('body', function ($list) { ?>
                    <div class="list-row list-row-name-<?= $list->get('data.html.name') ?: $list->getCurrentPositionName() ?><?php if ( $list->get('options.disabled') ) : ?> list-row-disabled<?php endif; ?><?php if ( $list->get('options.selected') ) : ?> list-row-selected<?php endif; ?>">
                        <?php if ( $list->get('options.template.big') ) : ?>
                            <div class="list-row-big">
                                <?php require $list->get('options.template.big'); ?>
                            </div>
                        <?php endif; ?>
                        <?php if ( $list->get('options.template.small') ) : ?>
                            <div class="list-row-small">
                                <?php require $list->get('options.template.small'); ?>
                            </div>
                        <?php endif; ?>
                        <?php if ( $list->get('options.template.medium') ) : ?>
                            <div class="list-row-medium">
                                <?php require $list->get('options.template.medium'); ?>
                            </div>
                        <?php endif; ?>
                    </div>
                <?php }); ?>
            </div>
        <?php else : ?>
            <?php if ( $list->get('data.empty') ) : ?>
                <div class="list-body">
                    <div class="list-row fw-600">
                        <?= $list->get('data.empty') ?>
                    </div>
                </div>
            <?php endif; ?>
        <?php endif; ?>
    </div>
<?php }); ?>