<div class="align wh-full">
    <div class="align wh-full checkbox group--<?= $input->get('data.group_class') ?>">
        <input id="g<?= $input->get('data.group_id') ?>" type="checkbox" name="category_permission_see[]" value="<?= $input->get('data.group_id') ?>"<?php if ( in_array($input->get('data.group_id'), $this->data->get('data.category.permission_see')) ?: []) : ?> checked<?php endif; ?>>
        <label for="g<?= $input->get('data.group_id') ?>">
            <span class="checkbox-icon">
                <i class="fa-solid fa-check"></i>
            </span>
        </label>
    </div>
</div>