<div class="checkbox">
    <label class="label label--<?= $option['data']['label_class_name'] ?>">
        <input id="<?= $option['data']['label_id'] ?>" type="checkbox" name="topic_label[]" value="<?= $option['data']['label_id'] ?>">
        <label for="<?= $option['data']['label_id'] ?>">
            <span class="checkbox-icon">
                <i class="fas fa-check"></i>
            </span>
            <?= $option['data']['label_name'] ?>
        </label>
    </label>
</div>