<a <?php if ($navbar->get('data.button_dropdown') == 0) : ?>href="<?= $navbar->get('data.button_link') ?: $navbar->get('data.button_sub_link') ?>"<?php endif; ?>>
    <?php if ( $navbar->get('data.button_icon') ) : ?>
        <i class="<?= $navbar->get('data.button_icon') ?>"></i>
    <?php endif; ?>
    <span>
        <?= $navbar->get('data.title') ?>
        <?php if ( $navbar->get('data.button_dropdown') == 1 ) : ?>
            <i class="fa fa-caret-down"></i>
        <?php endif; ?>
    </span>
</a>