<div class="navbar" js="navbar navbar-default">
    <div class="navbar-container container" js="navbar-body">
        <?php $this->data->navbar->each('body', function ($navbar) use ($build) { ?>
            <div class="navbar-content navbar-content-name-<?= $navbar->getCurrentPositionName() ?>" js="navbar-content">
                <?php $navbar->each('body', function ($navbar) use ($build) { ?>
                    <?php if ( $navbar->get('options.template.root') ) : ?>
                        <?php require $navbar->get('options.template.root'); return; ?>
                    <?php endif; ?>
                    <div class="navbar-button dropdown navbar-button-type-<?= $navbar->get('options.type') ?> navbar-button-name-<?= $navbar->getCurrentPositionName() ?>"<?php if ( $navbar->get('body') or $navbar->get('data.ajaxSelector') ) : ?> js="<?= $navbar->get('data.ajaxSelector') ?: 'dropdown' ?>"<?php endif; ?><?php if ( $navbar->get('data.ajax') ) : ?> ajax="<?= $navbar->get('data.ajax') ?>"<?php endif; ?>>
                        <?php if ( $navbar->get('options.template.body') ) : ?>
                            <?php require $navbar->get('options.template.body') ?>
                        <?php else : ?>
                            <a <?php if ( $navbar->get('data.href') ) : ?>href="<?= $navbar->get('data.href') ?>"<?php endif; ?><?php if ( $navbar->get('data.notifiCount') ) : ?> data-count="<?= $navbar->get('data.notifiCount') ?>"<?php endif; ?>>
                                <?php if ( $navbar->get('data.icon') ) : ?><i class="<?= $navbar->get('data.icon') ?>"></i><?php endif; ?>
                                <?php if ( $navbar->get('data.title') ) : ?>
                                    <span><?= $navbar->get('data.title') ?></span>
                                <?php endif; ?>
                                <?php if ( in_array($navbar->get('options.type'), ['menu', 'dropdown']) ) : ?><i class="fa fa-caret-down"></i><?php endif; ?>
                            </a>
                        <?php endif; ?>
                        <?php if ( $navbar->get('body') or $navbar->get('options.type') === 'menu' ) : ?>
                            <div class="dropdown-menu" js="dropdown-menu">
                                <div class="dropdown-content">
                                    <?php if ( $navbar->get('data.menu.title') ) : ?>
                                        <div class="dropdown-head"><?= $navbar->get('data.menu.title') ?></div>
                                    <?php endif; ?>
                                    <div class="dropdown-body" js="dropdown-body">
                                        <?php if ( $navbar->get('body') ) : ?>
                                            <?php $navbar->each('body', function ($navbar) { ?>
                                                <?php if ( $navbar->get('options.template.root') ) : ?>
                                                    <?php require $navbar->get('options.template.root'); return; ?>
                                                <?php endif; ?>
                                                <div class="dropdown-row" js="dropdown-row">
                                                    <?php if ( $navbar->get('options.template.body') ) : ?>
                                                        <?php require $navbar->get('options.template.body'); ?>
                                                    <?php else : ?>
                                                        <a <?php if ( $navbar->get('data.href') ) : ?>href="<?= $navbar->get('data.href') ?>"<?php endif; ?><?php if ( $navbar->get('data.ajax-action') ) : ?>ajax-action="<?= $navbar->get('data.ajax-action') ?>"<?php endif; ?>>
                                                            <span><?= $navbar->get('data.title') ?></span>
                                                        </a>
                                                    <?php endif; ?>
                                                </div>
                                            <?php }); ?>
                                        <?php else : ?>
                                            <?php if ( $navbar->get('data.empty') ) : ?>
                                                <div class="dropdown-row" js="dropdown-row">
                                                    <?= $navbar->get('data.empty') ?>
                                                </div>
                                            <?php endif; ?>
                                        <?php endif; ?>
                                    </div>
    
                                    <?php if ( $navbar->get('options.template.bottom') ) : ?>
                                        <?php if ( $navbar->get('body') ) : ?>
                                            <div class="dropdown-bottom">
                                                <?php require $navbar->get('options.template.bottom') ?>
                                            </div>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                </div>
                            </div>
                        <?php endif; ?>
                    </div>
                <?php }); ?>
            </div>
        <? }); ?>
    </div>
</div>