
<div class="page-column">
    <div class="page-column-icon"><i class="fa-solid fa-user"></i></div>
    <div class="page-column-title"><?= $language->get('L_ADMIN.L_ADMIN') ?></div>
    <?php if ($data->get('data.notice')) : ?>
        <div class="page-column-alert">
            <span><?= $data->get('data.notice') ?></span>
        </div>
    <?php endif; ?>
    <form method="post">
        <div class="page-column-body">
            <div class="page-column-input">
                <input type="text" name="user_name" placeholder="<?= $language->get('L_ADMIN.L_USERNAME') ?>" value="<?= $post->get('user_name') ?>"><i class="fa-solid fa-user"></i>
            </div>
            <div class="page-column-input">
                <input type="text" name="user_email" placeholder="<?= $language->get('L_ADMIN.L_EMAIL') ?>" value="<?= $post->get('user_email') ?>"><i class="fa-solid fa-envelope"></i>
            </div>
            <div class="page-column-input">
                <input type="password" name="user_password" placeholder="<?= $language->get('L_ADMIN.L_PASSWORD') ?>" value="<?= $post->get('user_password') ?>"><i class="fa-solid fa-key"></i>
            </div>
            <div class="field-submit">
                <input type="hidden" value="<?= SESSION_ID ?>" name="key">
                <input class="button" type="submit" name="submit" value="<?= $language->get('L_NEXT') ?>">
            </div>
        </div>
    </form>
</div>