<div class="page-column">
    <div class="page-column-icon"><i class="fas fa-language"></i></div>
    <div class="page-column-title"><?= $L_LANGUAGE ?></div>
    <?php if (isset($this->data->data['notice'])) : ?>
        <div class="page-column-alert">
            <span><?= $this->data->data['notice'] ?></span>
        </div>
    <?php endif; ?>
    <form method="post">
        <div class="page-column-body">
            <div class="page-column-select">
                <select name="language">
                    <?php foreach ($this->data->data['languages'] as $_language) :?>
                        <option value="<?= $_language['iso'] ?>"><?= $_language['name'] ?></option>
                    <?php endforeach; ?>
                </select>
                <i class="fas fa-language"></i>
                <i class="fas fa-chevron-down"></i>
            </div>
            <div class="field-submit">
                <input type="hidden" value="<?= SESSION_ID ?>" name="key">
                <input class="button" type="submit" name="submit" value="<?= $L_NEXT ?>">
            </div>
        </div>
    </form>
</div>