<div class="page-column">
    <div class="page-column-icon"><i class="fa-solid fa-gears"></i></div>
    <div class="page-column-title"><?= $language->get('L_SETTINGS.L_SETTINGS') ?></div>
    <?php if ($data->get('data.notice')) : ?>
        <div class="page-column-alert">
            <span><?= $data->get('data.notice') ?></span>
        </div>
    <?php endif; ?>
    <form method="post">
        <div class="page-column-body">
            <div class="page-column-input">
                <input type="text" name="name" placeholder="<?= $language->get('L_SETTINGS.L_NAME') ?>" value="<?= $post->get('name') ?>"><i class="fa-solid fa-heading"></i>
            </div>
            <div class="page-column-input">
                <input type="te
                " name="description" placeholder="<?= $language->get('L_SETTINGS.L_DESCRIPTION') ?>" value="<?= $post->get('description') ?>"><i class="fa-solid fa-align-justify"></i>
            </div>
            <div class="field-submit">
                <input type="hidden" value="<?= SESSION_ID ?>" name="key">
                <input class="button" type="submit" name="submit" value="<?= $language->get('L_NEXT') ?>">
            </div>
        </div>
    </form>
</div>