<div class="page-column">
    <div class="page-column-icon"><i class="fas fa-cogs"></i></div>
    <div class="page-column-title"><?= $L_SETTINGS_SETTINGS ?></div>
    <?php if (isset($this->data->data['notice'])) : ?>
        <div class="page-column-alert">
            <span><?= $this->data->data['notice'] ?></span>
        </div>
    <?php endif; ?>
    <form method="post">
        <div class="page-column-body">
            <div class="page-column-input">
                <input type="text" name="name" placeholder="<?= $L_SETTINGS_NAME ?>" value="<?= $this->form->get('name') ?>"><i class="fas fa-heading"></i>
            </div>
            <div class="page-column-input">
                <input type="te
                " name="description" placeholder="<?= $L_SETTINGS_DESCRIPTION ?>" value="<?= $this->form->get('description') ?>"><i class="fas fa-align-justify"></i>
            </div>
            <div class="field-submit">
                <input type="hidden" value="<?= SESSION_ID ?>" name="key">
                <input class="button" type="submit" name="submit" value="<?= $L_NEXT ?>">
            </div>
        </div>
    </form>
</div>