<div class="window window-mention" js="window-mention">
    <div class="window-mention-body" js="window-mention-body">
        <div class="window-mention-content">
            <div class="window-mention-background" js="window-mention-background"></div>
            <span js="window-mention-image"></span>
            <div class="window-mention-user" js="window-mention-user">
                <span js="window-mention-name"></span>
                <span js="window-mention-text"></span>
                <div class="window-mention-statues">
                    <span js="window-mention-group"></span>
                    <span js="window-mention-reputation"></span>
                    <span js="window-mention-role"></span>
                </div>
                <div class="window-mention-bottom">
                    <div class="table">
                        <div class="table-left">
                            <span js="window-mention-posts-lang"></span>:
                        </div>
                        <div class="table-right">
                            <span js="window-mention-posts-count"></span>
                        </div>
                    </div>
                    <div class="table">
                        <div class="table-left">
                            <span js="window-mention-topics-lang"></span>:
                        </div>
                        <div class="table-right">
                            <span js="window-mention-topics-count"></span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="window-arrow">
            <span></span>
        </div>
    </div>
</div>