<div class="window" js="window">
    <div class="window-content">
        <div class="window-head" js="window-head">
            <span js="window-title"></span>
        </div>
        <div class="window-body" js="window-body"></div>
        <div class="window-bottom" js="window-bottom">
            <a class="button button-confirm" ajax="confirm" js="window-submit"></a>
            <a class="button" ajax="window-close" js="window-cancel"></a>
        </div>
    </div>
</div>