<div class="navbar navbar-top">
    <div class="navbar-content">
        <div class="navbar-button">
            <a href="/Install/?repeat">
                <?php if ($this->data->data['page'] != 0) : ?>
                    <i class="fas fa-redo-alt"></i>
                    <span><?= $L_NAVBAR['L_REPEAT_INSTALLATION'] ?></span>
                <?php endif; ?>
            </a>
        </div>
        <div class="navbar-button" style="display: none;">
            <a ajax="collapse">
                <i class="fas fa-bars"></i>
            </a>
        </div>
    </div>
</div>
<div id="navbar" class="navbar navbar-side">
    <div class="navbar-content">
        <img src="/Uploads/Site/PHPCore.svg">
        <div class="navbar-button<?php if ($this->data->data['page'] == 0) : ?> navbar-button-active<?php endif; ?>">
            <div class="navbar-button-content">
                <a>
                    <span><i class="fas fa-home"></i> <?= $L_NAVBAR['L_START'] ?></span>
                </a>
            </div>
        </div>
        <div class="navbar-button<?php if ($this->data->data['page'] == 1) : ?> navbar-button-active<?php endif; ?>">
            <div class="navbar-button-content">
                <a>
                    <span><i class="fas fa-language"></i> <?= $L_NAVBAR['L_LANGUAGE'] ?></span>
                </a>
            </div>
        </div>
        <div class="navbar-button<?php if ($this->data->data['page'] == 2) : ?> navbar-button-active<?php endif; ?>">
            <div class="navbar-button-content">
                <a>
                    <span><i class="fas fa-database"></i> <?= $L_NAVBAR['L_DATABASE'] ?></span>
                </a>
            </div>
        </div>
        <div class="navbar-button<?php if ($this->data->data['page'] == 3) : ?> navbar-button-active<?php endif; ?>">
            <div class="navbar-button-content">
                <a>
                    <span><i class="fas fa-download"></i> <?= $L_NAVBAR['L_INSTALL'] ?></span>
                </a>
            </div>
        </div>
        <div class="navbar-button<?php if ($this->data->data['page'] == 4) : ?> navbar-button-active<?php endif; ?>">
            <div class="navbar-button-content">
                <a>
                    <span><i class="fas fa-user-cog"></i> <?= $L_NAVBAR['L_ADMIN'] ?></span>
                </a>
            </div>
        </div>
        <div class="navbar-button<?php if ($this->data->data['page'] == 5) : ?> navbar-button-active<?php endif; ?>">
            <div class="navbar-button-content">
                <a>
                    <span><i class="fas fa-cogs"></i> <?= $L_NAVBAR['L_SETTINGS_SETTINGS'] ?></span>
                </a>
            </div>
        </div>
        <div class="navbar-button<?php if ($this->data->data['page'] == 6) : ?> navbar-button-active<?php endif; ?>">
            <div class="navbar-button-content">
                <a>
                    <span><i class="fas fa-check-circle"></i> <?= $L_NAVBAR['L_INSTALLED'] ?></span>
                </a>
            </div>
        </div>
    </div>
</div>