<div class="vertical-align">
    <div class="profile">
        <img class="profile-image" src="<?= $row['data']['user_profile_image_url'] ?>" />
    </div>
    <div class="inner">
        <a class="list-title"><?= $row['data']['topic_name'] ?></a>
        <br>
        <?= $L_BY ?> <a href="<?= $row['data']['user_url'] ?>" class="fw-600"><?= $row['data']['user_name'] ?></a> <?= $this->build->date->short($row['data']['topic_created'], true) ?>
    </div>
</div>