<div class="list-row-align">
    <?= $this->build->user->image(data: $list->get('data')) ?>
    <div class="inner">
    <?php if ($list->get('data.report_reason_type') == 0 ) : ?>
        <?= $this->build->user->link(data: $list->get('data')) ?> <?= $this->build->date->long($list->get('data.report_reason_created'), true) ?>
        <br>
        <?= $list->get('data.report_reason_text') ?>
    <?php else : ?>
        <?= $this->build->date->long($list->get('data.report_reason_created'), true) ?>
        <br>
        <?= $this->build->user->link(data: $list->get('data')) ?> <?= $this->language->get('L_REPORT.L_CLOSED_BY') ?>
    <?php endif; ?>
    </div>
</div>