<form method="post" enctype="multipart/form-data">
    <div class="field">
        <div class="field-head">
            <span><?= $L_NAVBAR['L_ADMIN'] ?></span>
        </div>
        <div class="field-body">
            <div class="field-row">
                <div class="field-text">
                    <span class="title"><?= $L_ADMIN_USERNAME ?>:</span>
                </div>
                <div class="field-option">
                    <input type="text" name="user_name" placeholder="<?= $L_USERNAME ?>" value="<?= $form->get('user_name') ?>">
                </div>
            </div>
            <div class="field-row">
                <div class="field-text">
                    <span class="title"><?= $L_ADMIN_EMAIL ?>:</span>
                </div>
                <div class="field-option">
                    <input type="text" name="user_email" placeholder="<?= $L_EMAIL ?>" value="<?= $form->get('user_email') ?>">
                </div>
            </div>
            <div class="field-row">
                <div class="field-text">
                    <span class="title"><?= $L_ADMIN_PASSWORD ?>:</span>
                </div>
                <div class="field-option">
                    <input type="password" name="user_password" placeholder="<?= $L_PASSWORD ?>" value="<?= $form->get('user_password') ?>">
                </div>
            </div>
        </div>
    </div>

    <div class="field-submit">
        <input type="hidden" value="<?= SESSION_ID ?>" name="key">
        <input type="submit" name="submit" class="button" value="<?= $L_NEXT ?>">
    </div>
</form>