<html lang="cs-cz" class="html-hidden">
    <head>
        <meta charset="UTF-8">
        <title><?= $language->get('L_INSTALL') ?> | PHPCore</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <link rel="shortcut icon" type="image/x-icon" href="/Uploads/Site/PHPCore_icon.svg">

        <link rel="preload" as="font" type="font/woff2" href="/Install/Style/Themes/Fonts/Quicksand-Light.woff2?1" crossorigin>
        <link rel="preload" as="font" type="font/woff2" href="/Install/Style/Themes/Fonts/Quicksand-Regular.woff2?1" crossorigin>
        <link rel="preload" as="font" type="font/woff2" href="/Install/Style/Themes/Fonts/Quicksand-Medium.woff2?1" crossorigin>
        <link rel="preload" as="font" type="font/woff2" href="/Install/Style/Themes/Fonts/Quicksand-Bold.woff2?1" crossorigin>
        <link rel="stylesheet" type="text/css" href="/Install/Style/Themes/Stylesheet.css?<?= RAND ?>">
        <link rel="stylesheet" type="text/css" href="/Assets/FontAwesome/css/all.min.css">
    </head> 
    <body>
        <?php if (!in_array($data->get('data.page'), ['index', 'install-end', 'update-end'])) : ?>
            <a class="top-button" href="<?= $data->get('data.previous') ?>"><i class="fa-solid fa-chevron-left"></i> <?= $language->get('L_BTN.L_BACK') ?></a>
        <?php endif; ?>
        <?php if (in_array($data->get('data.page'), ['install-end', 'update-end'])) : ?>
            <a class="top-button" href="/menu/"><i class="fa-solid fa-chevron-left"></i> <?= $language->get('L_BACK_TO_INDEX') ?></a>
        <?php endif; ?>
        <?= $this->show() ?>
        <script>window.onload=function(){document.getElementsByTagName('html')[0].classList.remove('html-hidden');}</script>
    </body>
</html>