<img src="/Uploads/Site/PHPCore.svg">
<div class="page-button-list">
    <a class="page-button" href="?go=install"><?= $L_INSTALL ?></a>
    <a class="page-button" href="?go=update"><?= $L_UPDATE ?></a>
    <br>
    <br>
    <a class="page-button page-button-small" href="?go=extensions"><?= $L_EXTENSIONS ?></a>
    <a class="page-button page-button-small" href="?go=write"><?= $L_PERMISSION_WRITE ?></a>
</div>