<img src="/Uploads/Site/PHPCore.svg">
<div class="page-button-list">
    <a class="page-button" href="/install/database/"><?= $language->get('L_BTN.L_INSTALL') ?></a>
    <a class="page-button" href="/update/database/"><?= $language->get('L_BTN.L_UPDATE') ?></a>
    <br>
    <br>
    <a class="page-button page-button-small" href="/extensions/"><?= $language->get('L_BTN.L_EXTENSIONS') ?></a>
    <a class="page-button page-button-small" href="/permission/"><?= $language->get('L_BTN.L_PERMISSION') ?></a>
</div>