<div class="page-column">
    <div class="page-column-icon"><i class="fa-solid fa-language"></i></div>
    <div class="page-column-title"><?= $language->get('L_LANGUAGE') ?></div>
    <?php if ($data->get('data.notice')) : ?>
        <div class="page-column-alert">
            <span><?= $data->get('data.notice') ?></span>
        </div>
    <?php endif; ?>
    <form method="post">
        <div class="page-column-body">
            <div class="page-column-select">
                <select name="language">
                    <?php foreach ($data->get('data.languages') as $_) :?>
                        <option value="<?= $_['iso'] ?>"><?= $_['name'] ?></option>
                    <?php endforeach; ?>
                </select>
                <i class="fa-solid fa-language"></i>
                <i class="fa-solid fa-chevron-down"></i>
            </div>
            <div class="field-submit">
                <input type="hidden" value="<?= SESSION_ID ?>" name="key">
                <input class="button" type="submit" name="submit" value="<?= $language->get('L_NEXT') ?>">
            </div>
        </div>
    </form>
</div>