<form method="post" enctype="multipart/form-data">
    <div class="field">
        <div class="field-head">
            <span><?= $L_NAVBAR['L_SETTINGS_SETTINGS'] ?></span>
        </div>
        <div class="field-body">
            <div class="field-row">
                <div class="field-text">
                    <span class="title"><?= $L_SETTINGS_NAME ?>:</span>
                </div>
                <div class="field-option">
                    <input type="text" name="name" placeholder="<?= $L_NAME ?>" value="<?= $form->get('name') ?>">
                </div>
            </div>
            <div class="field-row">
                <div class="field-text">
                    <span class="title"><?= $L_SETTINGS_DESCRIPTION ?>:</span><?= $L_SETTINGS_DESCRIPTION_DESC ?>
                </div>
                <div class="field-option">
                    <input type="text" name="description" placeholder="<?= $L_DESCRIPTION ?>" value="<?= $form->get('description') ?>">
                </div>
            </div>
        </div>
    </div>

    <div class="field-submit">
        <input type="hidden" value="<?= SESSION_ID ?>" name="key">
        <input type="submit" name="submit" class="button" value="<?= $L_NEXT ?>">
    </div>
</form>