<?= $list->get('data.user_image') ?>
<div class="inner">
    <div class="label-list">
        <?php require $this->path->build('Root/Style:/Templates/Blocks/Labels.phtml'); ?>
        <?= $list->get('data.link')  ?>
    </div>
    <br>
    <span class="user">
        <?= $list->get('data.user') ?> · <?= $list->get('data.date')  ?>
    </span>
</div>
<?php if ( $list->get('data.topic_sticked') or $list->get('data.topic_locked') or $list->get('data.topic_attachments') or $list->get('data.topic_image') ) : ?>
    <div class="icons">
        <?php if ( $list->get('data.topic_attachments') ) : ?>
            <span class="icon-alt" ajax="title" ajax-title="<?= $this->language->get('L_TOPIC.L_ATTACHEMNT') ?>"><i class="fa-solid fa-paperclip"></i></span>
        <?php endif; ?>
        <?php if ( $list->get('data.topic_image') ) : ?>
            <span class="icon-alt" ajax="title" ajax-title="<?= $this->language->get('L_TOPIC.L_IMAGE.L_IMAGE') ?>"><i class="fa-solid fa-image"></i></span>
        <?php endif; ?>
        <?php if ( $list->get('data.topic_sticked') ) : ?>
            <span class="icon-alt" ajax="title" ajax-title="<?= $this->language->get('L_TOPIC.L_STICKED') ?>"><i class="fa-solid fa-thumbtack"></i></span>
        <?php endif; ?>
        <?php if ( $list->get('data.topic_locked') ) : ?>
            <span class="icon-alt" ajax="title" ajax-title="<?= $this->language->get('L_TOPIC.L_LOCKED') ?>"><i class="fa-solid fa-lock"></i></span>
        <?php endif; ?>
    </div>
<?php endif; ?>