<div class="vertical-align">
    <?= $this->build->user->image($row['data']) ?>
    <div class="inner">
        <span class="list-title"><?= $L_CONTENT_LIST[$row['data']['report_type']] ?></span>
        <?php if ($row['data']['report_status'] == 0) : ?>
            <span class="text-warning"> <?= $L_REPORT_UNRESOLVED ?></span>
        <?php endif; ?>
        <br>
        <?= $L_BY ?> <?= $this->build->user->link($row['data'], true) ?>
    </div>
</div>