<div id="new" class="block block-form" js="block block-form" ajax-id="<?= $block->get('data.html.ajax-id') ?>" ajax-item="post">
    <form method="post">
        <div class="block-head">
            <?= $this->build->user->image(data: $this->user->get(), size: '50x50') ?>
            <div class="inner">
                <div class="label-list"><span><?= $this->language->get('L_RE') ?>: <?= $block->get('data.topic_name') ?></span></div>
                <a class="button f-right" ajax-action="create"><?= $this->language->get('L_BTN.L_SUBMIT') ?></a>
                <input type="hidden" name="key" value="<?= SESSION_ID ?>">
            </div>
        </div>
        <textarea name="post_text" trumbowyg="big" placeholder="<?= $this->language->get('L_PLACEHOLDER.L_TEXT') ?>"></textarea>
    </form>
</div>