<div class="block block-clear" js="block block-form" ajax-id="<?= $this->data->get('data.profile_post_id') ?: $block->get('data.profile_post_id') ?>" ajax-item="profile-post-comment">
    <form method="post">
        <div class="block-body">
            <a class="button" ajax-action="create" js="button">
                <i class="fa-solid fa-check"></i>
            </a>
            <?= $this->build->user->image($this->data->get('inst.user')->get()) ?>
            <textarea ajax="textarea" name="profile_post_comment_text" placeholder="<?= $this->language->get('L_PROFILE_POST.L_ANSWER') ?>"></textarea>
            <input type="hidden" value="<?= SESSION_ID ?>" name="key">
        </div>
    </form>
</div>