<div id="c0" class="block block-two-column block-mini block-border" ajax-selector="block">
    <div class="block-* wh-full">
        <div class="block-body" ajax-selector="block-body">
            <div class="block-head">
                <a class="a-reverse" ajax="next-comments" data-id="<?= $cache['data']['id'] ?>"><?= $L_SHOW_PREVIOUS_COMMENTS ?></a>
            </div>
        </div>
    </div>
</div>