<div id="c0" class="block block-name-previous-profile-comments block-two-column block-mini block-border" js="block" ajax-item="profile-post" ajax-id="<?= $block->get('data.profile_post_id') ?>">
    <div class="block-* wh-full">
        <div class="block-body" js="block-body">
            <div class="block-head">
                <a class="a-reverse" ajax-action="previous"><?= $this->language->get('L_SHOW_PREVIOUS_COMMENTS') ?></a>
            </div>
        </div>
    </div>
</div>