<div id="c0" class="block block-two-column block-mini block-border" ajax-selector="block" ajax-process-type="/ProfilePostComment" ajax-process-id="<?= $cache['data']['id'] ?>">
    <div class="block-* wh-full">
        <div class="block-body" ajax-selector="block-body">
            <div class="block-head">
                <a class="a-reverse" ajax="get" ajax-process="/Previous"><?= $L_SHOW_PREVIOUS_COMMENTS ?></a>
            </div>
        </div>
    </div>
</div>