<div id="p0" class="block block-clear block-margin" js="block block-form" ajax-id="<?= $this->data->get('data.profile.user_id') ?>" ajax-item="profile-post">
    <form method="post" id="form">
        <div class="block-body ">
            <a class="button" ajax-action="create" js="button">
                <i class="fa-solid fa-check"></i>
            </a>
            <?= $this->build->user->image(data: $this->data->get('inst.user')->get(), size: '25x25') ?>
            <textarea ajax="textarea" name="profile_post_text" <?php if ($this->data->get('data.profile.user_id') == LOGGED_USER_ID) : ?> placeholder="<?= $this->language->get('L_PROFILE_POST.L_MESSAGE_TO_MY_PROFILE') ?>" <?php else : ?> placeholder="<?= $this->language->get('L_PROFILE_POST.L_MESSAGE_TO_PROFILE') ?>" <?php endif; ?> ></textarea>
            <input type="hidden" value="<?= SESSION_ID ?>" name="key">
        </div>
    </form>
</div>