<a>
    <label for="f<?= $panel->get('data.forum_id') ?>">
        <?= $panel->get('data.forum_name') ?>
    </label>
    <div class="radio">
        <input id="f<?= $panel->get('data.forum_id') ?>" type="radio" name="new_forum_id" value="<?= $panel->get('data.forum_id') ?>"<?php if ($panel->get('options.checked')) : ?> checked<?php endif; ?>>
        <label for="f<?= $panel->get('data.forum_id') ?>">
            <div></div>
        </label>
    </div>
</a>