<div class="align wh-full">
    <div class="align wh-full checkbox group--<?= $row['data']['group_class_name'] ?>">
        <input id="g<?= $row['data']['group_id'] ?>" type="checkbox" name="category_permission_see[]" value="<?= $row['data']['group_id'] ?>"<?= in_array($row['data']['group_id'], isset($this->data->field['_data']['see']) ? $this->data->field['_data']['see'] : []) ? ' checked' : '' ?>>
        <label for="g<?= $row['data']['group_id'] ?>">
            <span class="checkbox-icon">
                <i class="fas fa-check"></i>
            </span>
        </label>
    </div>
</div>