<?php foreach ((array)$this->data->sidebar['body'] as $objectName => $object) : ?>
    <div class="list list-small list-type-<?= $object['options']['type'] ?? '' ?> list-name-<?= $objectName ?>">
        <div class="list-head">
            <span><?= ${$object['data']['title']} ?></span>
        </div>
        <div class="list-body">     
            <?php if (isset($object['options']['type']) and $object['options']['type'] === 'table') : ?>
                <div class="list-row">
                    <?php foreach ($object['body'] as $row) : ?>
                        <div class="table">
                            <div class="table-left"><?= ${$row['data']['title']} ?>:</div>
                            <div class="table-right"><?= $row['data']['value'] ?></div>
                        </div>
                    <?php endforeach; ?>
                </div>
            <?php else : ?>

                <?php if (isset($object['options']['type']) and $object['options']['type'] === 'list') : ?>
                    <div class="list-row">
                        <div class="commas">
                        <?php if (!empty($object['body'] )) : ?>
                            <?php foreach ($object['body'] as $row) : ?>
                                <?php require $row['options']['template']['body']; ?>
                            <?php endforeach; ?>
                        <?php else : ?>
                            <?php if (isset($object['options']['empty'])) : ?>
                                <?= ${$object['options']['empty']} ?>
                            <?php endif; ?>
                        <?php endif; ?>
                        </div>
                    </div>
                <?php else : ?>
                    <?php if (!empty($object['body'] )) : ?>
                        <?php foreach ((array)$object['body'] as $rowName => $row) : ?>
                            <div class="list-row list-row-name-<?= $rowName ?>" ajax-selector="list-row">
                                <?php if (isset($row['options']['template']['body'])) : ?>
                                    <?php require $row['options']['template']['body']; ?>
                                <?php else : ?>
                                    <a href="<?= $row['data']['href'] ? $this->system->url->build($row['data']['href']) : '' ?>"><i class="<?= $row['data']['icon'] ?>"></i> <?= ${$row['data']['title']} ?></a>
                                <?php endif; ?>
                            </div>
                        <?php endforeach; ?>
                    <?php else : ?>
                        <?php if (isset($object['options']['empty'])) : ?>
                            <div class="list-row">
                                <?= ${$object['options']['empty']} ?>
                            </div>
                        <?php endif; ?>
                    <?php endif; ?>
                <?php endif; ?>
            <?php endif; ?>
        </div>
    </div>
<?php endforeach; ?>