<div class="navbar navbar-side navbar-default" js="navbar navbar-side">
    
    <img src="/Uploads/Site/PHPCore.svg">

    <?php $this->data->navbar->each('body', function ($navbar) use ($url) { ?>

        <?php if ( $navbar->get('options.permission') ) : ?>
            <?php if ($this->user->perm->has($navbar->get('options.permission')) === false) : ?>
                <?php return; ?>
            <?php endif; ?>
        <?php endif; ?>

        <div class="navbar-content<?php if ( $navbar->get('options.disabled') ) : ?> navbar-content-disabled<?php endif; ?>">
            <?php if ( $navbar->get('data.title') ) : ?>
                <div class="navbar-button navbar-category">
                    <span><span><?= $navbar->get('data.title') ?></span><?php if ( $navbar->get('options.disabled') ) : ?><i class="fa-solid fa-lock"></i><?php endif; ?></span>
                </div>
            <?php endif; ?>
            <?php $navbar->each('body', function ($navbar) use ($url) { ?>

                <?php if ( $navbar->get('options.permission') ) : ?>
                    <?php if ($this->user->perm->has( $navbar->get('options.permission')) === false) : ?>
                        <?php return; ?>
                    <?php endif; ?>
                <?php endif; ?>
                <div class="navbar-button<?php if ( $navbar->get('options.disabled') ) : ?> navbar-button-disabled<?php endif; ?><?php if ( $navbar->get('body') and !$navbar->get('options.disabled') ) : ?> navbar-dropdown navbar-dropdown-name-<?= $navbar->getCurrentPositionName() ?><?php endif; ?><?php if ($navbar->get('options.active')) : ?> <?= ( $navbar->get('body') ) ? 'navbar-dropdown-opened' : 'navbar-button-active' ?><?php endif; ?>" js="dropdown">
                    <div class="navbar-button-content" js="dropdown-content">
                        <a <?php if ( $navbar->get('data.href') and !$navbar->get('options.disabled') ) : ?>href="<?= $url->build($navbar->get('data.href')) ?>"<?php endif; ?>>
                            <i class="<?= $navbar->get('data.icon') ?>"></i>
                            <span <?php if ( $navbar->get('data.notifiCount') and !$navbar->get('options.disabled') ) : ?>data-count="<?= $navbar->get('data.notifiCount') ?>"<?php endif; ?><?php if ( $navbar->get('data.notifiIcon') ) : ?> data-icon="&#x<?= $navbar->get('data.notifiIcon') ?>"<?php endif; ?>><?= $navbar->get('data.title') ?></span>
                            <?php if ( $navbar->get('options.disabled') ) : ?>
                                <i class="fa-solid fa-lock"></i>
                            <?php endif; ?>
                        </a>
                        <?php if ( $navbar->get('body') and !$navbar->get('options.disabled')) : ?>
                            <a class="navbar-button-arrow" js="open-dropdown">
                                <i class="arrow<?php if ( $navbar->get('options.active') ) : ?> d-none<?php endif; ?> fa-solid fa-angle-left" js="arrow-left"></i>
                                <i class="arrow<?php if ( !$navbar->get('options.active') ) : ?> d-none<?php endif; ?> fa-solid fa-angle-down" js="arrow-down"></i>
                            </a>
                        <?php endif; ?>
                    </div>
                    <?php if ($navbar->get('body') and !$navbar->get('options.disabled')) : ?>
                        <div class="dropdown-menu" js="dropdown-menu">
                            <div class="dropdown-content">
                                <div class="dropdown-body" js="dropdown-body">
                                    <?php $navbar->each('body', function ($navbar) use ($url) { ?>
                                        <div class="dropdown-row dropdown-row-name-<?= $navbar->getCurrentPositionName() ?><?php if ($navbar->get('options.active')) : ?> dropdown-row-active<?php endif; ?>" js="dropdown-row">
                                            <a <?php if ( $navbar->get('data.href') and !$navbar->get('options.disabled') ) : ?>href="<?= $url->build($navbar->get('data.href')) ?>"<?php endif; ?>>
                                                <span <?php if ( $navbar->get('data.notifiCount') ) : ?>data-count="<?= $navbar->get('data.notifiCount') ?>"<?php endif; ?>><?= $navbar->get('data.title') ?></span>
                                                <?php if ( $navbar->get('options.disabled') ) : ?>
                                                    <i class="fa-solid fa-lock"></i>
                                                <?php endif; ?>
                                            </a>
                                        </div>
                                    <?php }); ?>
                                </div>
                            </div>
                        </div>
                    <?php endif; ?>
                </div>
            <?php }); ?>
        </div>
    <?php }); ?>
</div>