<div class="block-inner m-top fw-600" ajax-selector="likes">
    <span>
        <span class="like" ><i class="fas fa-thumbs-up"></i></span> x <span class="count" ajax-selector="count"><?= isset($row) ? $row['data']['count_of_likes'] : '' ?></span>
    </span>
    <span class="commas" ajax-selector="list">
        <?php if (isset($row)) : ?>
            <?php foreach ($row['data']['likes'] as $username) : ?>
                <?php if ($this->user->isLogged() and $username['user_id'] == LOGGED_USER_ID) : ?>
                    <span><?= $L_YOU ?></span>
                <?php else : ?>
                    <?= $this->build->user->link($username) ?>
                <?php endif; ?>
            <?php endforeach; ?>
            <?php if ($row['data']['is_more_likes'] == 1) : ?>
                <a ajax="all-likes">... <?= $L_LIKES_MORE ?> <?= (int)$row['data']['count_of_likes'] - 5 ?></a>
            <?php endif; ?>
        <?php endif; ?>
    </span>
</div>