<!DOCTYPE html>
<html id="html" lang="cs-cz" class="html-hidden html-<?= $this->data->get('data.page-html') ?>">

    <?php require $path->build('Root/Style:/Templates/Blocks/Head.phtml'); ?>
    <body>

        <div class="navbar navbar-mobile" js="navbar navbar-mobile"></div>
        <div class="page" js="page">
    
            <?php require $path->build('Root/Style:/Templates/Blocks/Visualization/Navbar/Navbar.phtml'); ?>
            
            <div class="header<?php if ($template->get('settings.background_image_position')) : ?> header-align-<?= $template->get('settings.background_image_position') ?><?php endif; ?><?php if ($this->data->get('options.header')) : ?> header-type-big<?php endif; ?>"<?php if ( $template->get('settings.background_image') ) : ?> style="background-image: url('<?= $template->get('settings.background_image') ?>');"<?php endif; ?>>
                <div class="header-overlay"></div>
                <div class="header-container container">
                    <?php if ($this->data->get('options.header') === true) : ?>
                        <h1><?= $system->get('site_name') ?></h1>
                        <h2><?= $this->data->get('data.head.description') ?></h2>
                    <?php else : ?>
                        <h1><?= $this->data->get('data.head.title') ?></h1>
                    <?php endif; ?>
                </div>
            </div>


            <?php require $path->build('Root/Style:/Templates/Blocks/Visualization/Breadcrumb/Breadcrumb.phtml') ?>
            <div class="page-body">
                <div class="page-container container">
                
                    <?php require $path->build('Root/Style:/Templates/Blocks/Alert.phtml') ?>
                    <?php require $path->build('Root/Style:/Templates/Blocks/Notification.phtml') ?>

                    <?php if ($this->data->get('options.profileHeader') === true) : ?>
                        <div class="page-content-profile-header" <?php if ($this->data->get('data.profile.user_header_image')) : ?>style="background-image: url(/Uploads/Users/<?= $this->data->get('data.profile.user_id') ?>/Header.<?= $this->data->get('data.profile.user_header_image') ?>)"<?php endif; ?>></div>
                    <?php endif; ?>


                    <div class="page-content">
                        <?php if ( $this->data->sidebar->get('options.side') == 'left' and $this->data->sidebar->get('body') ) : ?>
                            <div class="page-content-side page-content-side-align-left page-content-side-type-<?= $this->data->sidebar->get('options.type') ?>">
                                <?php require $path->build('Root/Style:/Templates/Blocks/Visualization/Sidebar/Sidebar.phtml'); ?>
                            </div>
                        <?php endif; ?>
                        <div class="page-content-middle">
                            <?php $this->show(); ?>
                        </div>
                        <?php if ( $this->data->sidebar->get('options.side') == 'right' and $this->data->sidebar->get('body') ) : ?>
                            <div class="page-content-side page-content-side-align-right page-content-side-type-<?= $this->data->sidebar->get('options.type') ?>">
                                <?php require $path->build('Root/Style:/Templates/Blocks/Visualization/Sidebar/Sidebar.phtml'); ?>
                            </div>
                        <?php endif; ?>
                    </div>
                </div>
            </div>
            <?php require $path->build('Root/Style:/Templates/Blocks/Footer.phtml'); ?>
        </div>
        <div class="opacity" js="opacity"></div>
        <?php require $path->build('Root/Style:/Templates/Blocks/Title.phtml'); ?>
        <?php require $path->build('Root/Style:/Templates/Blocks/Window/Window.phtml'); ?>
        <?php require $path->build('Root/Style:/Templates/Blocks/Window/Alert.phtml'); ?>
        <?php require $path->build('Root/Style:/Templates/Blocks/Window/Mention.phtml'); ?>
        <?php require $path->build('Root/Style:/Templates/Blocks/Loading.phtml'); ?>
        <?php require $path->build('/Includes/Template/Footer.phtml'); ?>
    </body>
</html>