<!DOCTYPE html>
<html id="html" lang="cs-cz" class="html-full html-hidden <?= $this->data->data['pageName'] ?>">

    <head>
        <?php require $this->template->template('/Blocks/Head.phtml'); ?>
    </head>

    <body>

        <div class="page">

            <?php $this->show(); ?>
        </div>
        <?php require $this->template->template('/Blocks/Cookie.phtml'); ?>
        <?php require ROOT . '/Includes/Template/Footer.phtml' ?>
    </body>
    
</html>