<!DOCTYPE html>
<html id="html" lang="cs-cz" class="html-full html-hidden html-<?= $this->data->get('data.page-html') ?>">

    <head>
        <?php require $path->build('Root/Style:/Templates/Blocks/Head.phtml'); ?>
    </head>

    <body>

        <div class="page">

            <?php $this->show(); ?>
        </div>
        <?php require ROOT . '/Includes/Template/Footer.phtml' ?>
    </body>
    
</html>