<div class="tab">
    <a ajax="tab" data-name="default" class="tab-button tab-button-active"><?= $L_PROFILE_POSTS ?></a>
    <?php if (!empty($this->data->data['user_signature'])) : ?>
        <a ajax="tab" data-name="signature" class="tab-button"><?= $L_USER_SIGNATURE ?></a>
    <?php endif; ?>
</div>
<div class="tab-content" ajax-selector="tab-content tab-content-default">

    <?php require ROOT . '/Includes/Object/Visualization/Block/Templates/ProfilePostNew.phtml' ?>

    <?php if (isset($this->data->pagination['enabled']) and $this->data->pagination['enabled'] == true) : ?>
        <div class="panel panel-top">
            <?php require $this->template->template('/Blocks/Pagination.phtml'); ?>
        </div>
    <?php endif; ?>
    <div class="block-list" ajax-selector="block-list">
        <?php require $this->template->template('/Blocks/Visualization/Block/ProfilePost.phtml'); ?>

        <?php if (empty($this->data->block['body']['profilepost']['body'])) : ?>
            <div class="block" ajax-selector="block block-empty">
                <div class="block-body"><?= strtr($L_PROFILE_POST_NO, ['{user_name}' => $this->data->data['user_name']]) ?></div>
            </div>
        <?php endif; ?>

    </div>
    <?php require $this->template->template('/Blocks/Pagination.phtml'); ?>
</div>

<?php if (!empty($this->data->data['user_signature'])) : ?>
    <div class="tab-content" ajax-selector="tab-content tab-content-signature">
        <div class="field">
            <div class="field-row field-row-grid">
                <div class="field-text"><?= $this->data->data['user_signature'] ?></div>
            </div>
        </div>
    </div>
<?php endif; ?>