<div class="page-column page-column-big">
    <div class="page-column-icon"><i class="fa-solid fa-list"></i></div>
    <div class="page-column-title"><?= $language->get('L_REGISTER.L_TERMS') ?></div>
    <div class="page-column-description">
        <span><?= $system->get('registration_terms') ?></span>
    </div>
    <?= $this->data->get('data.links.register') ?>
    <hr>
    <?= $this->data->get('data.links.login') ?>
</div>