<?php if (isset($row['data']['color']) and $row['data']['color'] === 'green') : ?>
    <i class="fas fa-green fa-check-circle"></i>
<?php else : ?>
    <i class="fas fa-red fa-times-circle"></i>
<?php endif; ?>
<?php if (isset($row['data']['titleIcon'])) : ?>
    <span>
        <?= str_starts_with($row['data']['titleIcon'], '$') ? substr($row['data']['titleIcon'], 1) : ${$row['data']['titleIcon']} ?>
    </span>
<?php endif; ?>