<div class="list-row-align">
    <div class="list-row-icon"><?php if ($list->get('data.forum_main')) : ?><i class="fa-solid fa-star"></i><?php endif; ?></div>
    <?php if ($list->get('data.forum_icon')) : ?>
        <div class="list-row-icon"><i class="<?= $list->get('data.forum_icon') ?>"></i></div>
    <?php endif; ?>
    <div>
        <span class="list-title"><?= $list->get('data.forum_name') ?></span>
        <br>
        <span class="title-sub"><?= $list->get('data.forum_description') ?></span>
    </div>
</div>