<?php $this->data->list->each('body', function ($list) use ($path, $language, $url, $build) { ?>

    <?php if ( $list->get('options.type') == 'grid' ) : ?>
        <div class="list list-name-<?= $list->getCurrentPositionName() ?> list-grid" js="list">
            <?php if ( $list->get('data.title') ) : ?>
                <div class="list-head">
                    <div class="list-row-big">
                        <span><?= $list->get('data.title') ?></span>
                    </div>
                </div>
            <?php endif; ?>
            <div class="list-body" js="list-body">
                <?php $list->each('body', function ($list) use ($path, $language, $url, $build) { ?>
                    <div class="list-row list-row-name-<?= $list->getCurrentPositionName() ?><?php if ( $list->get('options.disabled') ) : ?> list-row-disabled<?php endif; ?>" js="list-row<?php if ( $list->get('options.disabled') ) : ?> list-row-disabled<?php endif; ?>" ajax-item="<?= $list->get('data.html.ajax-item') ?>" ajax-id="<?= $list->get('data.html.ajax-id') ?>">
                        <?php $list->each('data.label', function ($label) { ?>
                            <div class="list-row-label list-row-label-<?= $label->get('color') ?>"><?= $label->get('text') ?></div>
                        <?php }); ?>
                        <?php if ( $list->get('data.image') ) : ?>
                            <div class="list-row-image" style="background-image: url('<?= $list->get('data.image') ?>')"></div>
                        <?php endif; ?>
                        <div class="list-row-inner" js="list-row-inner">
                            <div class="list-row-body">
                                <div class="list-row-big">
                                    <span class="list-title">
                                        <span><?= str_starts_with($list->get('data.title'), '$') ? substr($list->get('data.title') , 1) : $list->get('data.title') ?></span>
                                        <span><?= $list->get('data.version.version') ?></span>
                                    </span>
                                    <span class="fw-600"><?= $language->get('L_AUTHOR') ?></span>: <?php if ( $list->get('data.author.link') ) : ?><a class="username" target="_blank" href="<?= $list->get('data.author.link') ?>"><span><?= $list->get('data.author.name') ?></span><i class="fa-solid fa-share"></i></a><?php else : ?><span><?= $list->get('data.author.name') ?></span><?php endif; ?>
                                    <br>
                                    <?php if ( $list->get('data.desc') ) : ?>
                                        <span><?= str_starts_with($list->get('data.desc'), '$') ? substr($list->get('data.desc') , 1) : $list->get('data.desc') ?></span>
                                    <?php endif; ?>
                                </div>
                                <?php if ( $list->get('data.button') ) : ?>
                                    <div class="list-row-medium" js="list-row-medium">
                                        <?php require $path->build('Root/Style:/Templates/Blocks/Visualization/Lists/ListsButton.phtml'); ?>
                                    </div>
                                <?php endif; ?>
                            </div>
                        </div>
                    </div>
                <?php }); ?>
                <?php if ( !$list->get('body') and $list->get('data.empty') ) : ?>
                    <div class="list-row">
                        <div class="list-row-inner" js="list-row-inner">
                            <div class="list-row-body">
                                <div class="list-row-big">
                                    <span class="list-title"><?= $list->get('data.empty') ?></span>
                                </div>
                            </div>
                        </div>
                    </div>
                <?php endif; ?>
            </div>
        </div>
    <?php else : ?>
        <div class="list list-name-<?= $list->getCurrentPositionName() ?>" js="list">
            <div class="list-head">
                <div class="list-row-big<?php if ( empty($list->get('data.desc')) ) : ?> vertical-align<?php endif; ?>">
                    <span class="inner">
                        <span><?= $list->get('data.title') ?></span>
                        <?php if ( $list->get('data.desc') ) : ?>
                            <br>
                            <span class="list-head-description"><?= $list->get('data.desc') ?></span>
                        <?php endif; ?>  
                    </span>
                </div>
                <?php if ( $list->get('data.button') or (isset($this->data->pagination['enabled'])) and $this->data->pagination['enabled'] === true) : ?>
                    <div class="list-row-medium">
                        <?php if ( $list->get('data.button') ) : ?>
                            <?php require $path->build('Root/Style:/Templates/Blocks/Visualization/Lists/ListsButton.phtml'); ?>
                        <?php endif; ?>
                        <?php if (isset($this->data->pagination['enabled'])) : ?> 
                            <?php if ($this->data->pagination['enabled'] === true) : ?> 
                                <?php require $path->build('Root/Style:/Templates/Blocks/Pagination.phtml') ?>
                            <?php endif; ?>
                        <?php endif; ?>
                    </div>
                <?php endif; ?>
            </div>
            <div class="list-body" js="list-body">
                <?php $list->each('body', function ($list) use ($path, $language, $url, $build) { ?>
                    <div class="list-row list-row-name-<?= $list->getCurrentPositionName() ?> <?php if ( $list->get('options.disabled') ) : ?> list-row-disabled<?php endif; ?>" js="list-row<?php if ( $list->get('options.disabled') ) : ?> list-row-disabled<?php endif; ?>" ajax-item="<?= $list->get('data.html.ajax-item') ?>" ajax-id="<?= $list->get('data.html.ajax-id') ?>">
                        <div class="list-row-inner" js="list-row-inner">
                            <?php $list->each('data.label', function ($label) { ?>
                                <div class="list-row-label list-row-label-<?= $label->get('color') ?>">
                                    <?php if ( $label->get('icon') ) : ?>
                                        <i class="<?= $label->get('icon') ?>"></i>
                                    <?php else : ?>
                                        <?= $label->get('text') ?>
                                    <?php endif; ?>
                                </div>
                            <?php }); ?>
                            <div class="list-row-body" js="list-row-body">
                                <div class="list-row-big<?php if ( !$list->get('data.desc') and !$list->get('options.template.big') ) : ?> vertical-align<?php endif; ?>">
                                    <?php require $path->build('Root/Style:/Templates/Blocks/Visualization/Lists/ListsRow.phtml'); ?>
                                </div>
                                <?php if ( $list->get('data.button') ) : ?>
                                    <div class="list-row-medium" js="list-row-medium">
                                        <?php require $path->build('Root/Style:/Templates/Blocks/Visualization/Lists/ListsButton.phtml'); ?>
                                    </div>
                                <?php endif; ?>
                            </div>
                        </div>
                        <?php if ( $list->get('body') ) : ?>
                            <div class="list-row-body" js="list-row-body">
                                <div class="list-body" js="list-body">
                                    <?php $list->each('body', function ($list) use ($path, $language, $url, $build) { ?>
                                        <div class="list-row" js="list-row" ajax-item="<?= $list->get('data.html.ajax-item') ?>" ajax-id="<?= $list->get('data.html.ajax-id') ?>">
                                            <div class="list-row-inner" js="list-row-inner">
                                                <div class="list-row-body" js="list-row-body">
                                                    <div class="list-row-big">
                                                        <?php require $path->build('Root/Style:/Templates/Blocks/Visualization/Lists/ListsRow.phtml'); ?>
                                                    </div>
                                                    <?php if ( $list->get('data.button') ) : ?>
                                                        <div class="list-row-medium" js="list-row-medium">
                                                            <?php require $path->build('Root/Style:/Templates/Blocks/Visualization/Lists/ListsButton.phtml'); ?>
                                                        </div>
                                                    <?php endif; ?>
                                                </div>
                                            </div>
                                        </div>
                                    <?php }); ?>
                                </div>
                            </div>
                        <?php endif; ?>
                    </div>
                <?php }); ?>
                <?php if ( empty($list->get('body')) and $list->get('data.empty') ) : ?>
                    <div class="list-row">
                        <div class="list-row-inner" js="list-row-inner">
                            <div class="list-row-body">
                                <div class="list-row-big">
                                    <span class="list-title"><?= $list->get('data.empty') ?></span>
                                </div>
                            </div>
                        </div>
                    </div>
                <?php endif; ?>
            </div>
        </div>
    <?php endif; ?>
<?php }); ?>