<?php if ( $list->get('options.template.big') ) : ?>
    <?php require $list->get('options.template.big'); ?>
<?php else : ?>
    <span class="list-title"><?= str_starts_with($list->get('data.title'), '$') ? substr($list->get('data.title') , 1) : $list->get('data.title') ?></span>
    <?php if ( $list->get('data.desc') ) : ?>
        <br>
        <span><?= str_starts_with($list->get('data.desc'), '$') ? substr($list->get('data.desc') , 1) : $list->get('data.desc') ?></span>
    <?php endif; ?>
<?php endif; ?>