<?php $list->each('data.button', function ($button) use ($list, $url, $language) { ?>
    <?php if ( $button->get('template') and is_string($button->get('template'))) : ?>
        <?php require $button->get('template'); ?>
    <?php else : ?>
        <a class="button button-<?= $button->getCurrentPositionName() ?><?php if ( $button->get('disabled') ) : ?> button-disabled<?php endif; ?><?php if ( !$button->get('title') ) : ?> button-icon<?php endif; ?>" <?php if ( $button->get('href') ) : ?>href="<?= $button->get('href') ?>"<?php else : ?> ajax-action="<?= $button->get('ajax-action') ?: $button->getCurrentPositionName() ?>"<?php endif; ?><?php if ( $button->get('target') ) : ?> target="<?= $button->get('target') ?>"<?php endif; ?>>
            <?php if ( $button->get('icon') ) : ?><i class="<?= $button->get('icon') ?>"></i><?php endif; ?>
            <?php if ( $button->get('title') ) : ?><span><?= $button->get('title') ?></span></i><?php endif; ?>
        </a>
    <?php endif; ?>
<?php }); ?>