<div class="list-row-align">
    <?= $this->build->user->image($list->get('data')) ?>
    <div class="inner">
        <?= $this->build->user->link(data: $list->get('data')) ?> <?= $language->get('L_LOG.L_PROTOCOL.' . $list->get('data.log_action')) ?><span class="fw-600"><?= $list->get('data.log_text') ? ' ' . $list->get('data.log_text') : '' ?></span>.<br><?= $this->build->date->long($list->get('data.log_created'), true) ?>
    </div>
</div>
