<div class="list-row-align">
    <div class="profile">
        <img class="profile-image" src="<?= $list->get('data.user_profile_image_url') ?>" />
    </div>
    <div class="inner">
        <a class="list-title"><?= $list->get('data.topic_name') ?></a>
        <br>
        <?= $language->get('L_BY') ?> <a href="<?= $list->get('data.user_url') ?>" class="fw-600"><?= $list->get('data.user_name') ?></a>
    </div>
</div>