<div class="list-row-align">
    <span class="list-row-icon"><?php if ($this->system->get('site.mode') == 'blog' and $list->get('data.desc')) : ?><i class="fa-solid fa-eye-slash"></i><?php else : ?><i class="fa-solid fa-eye"></i><?php endif; ?></span>
    <div>
        <span class="list-title"><?= $list->get('data.sidebar_object') ?></span>
        <br>
        <span><?= $list->get('data.desc') ?></span>
    </div>
</div>
