<?php if ( $this->data->block->get('body') ) : ?>
    <div class="block-list">
        <?php $this->data->block->each('body', function ($block) { ?>
            <div class="block block-<?= $block->get('data.color') ?>">
                <div class="block-content">
                    <span class="block-number">
                        <?php if ( $block->get('data.href') ) : ?>
                            <a target="_blank" href="<?= $block->get('data.href') ?>">
                                <span><?= $block->get('data.value') ?></span>
                                <i class="fa-solid fa-share"></i>
                            </a>
                        <?php else : ?>
                            <span><?= $block->get('data.value') ?></span>
                        <?php endif; ?>
                    </span>
                    <br>
                    <span class="block-title"><?= $block->get('data.title') ?></span>
                </div>
                <div class="block-icon">
                    <i class="<?= $block->get('data.icon') ?>"></i>
                </div>
            </div>
        <?php }); ?>
    </div>
<?php endif; ?>