<?php $this->data->block->each('body', function ($block) { ?>
    <?php if ($block->get('options.template')) : ?>
        <?php require $block->get('options.template'); return; ?>
    <?php endif; ?>
    <?php $block->each('body', function ($block) { ?>
        <?php if ($block->get('options.template')) : ?>
            <?php require $block->get('options.template'); return; ?>
        <?php endif; ?>
        <div id="<?= $block->get('data.html.ajax-id') ?>" class="block block-name-<?= $block->getCurrentPositionName() ?><?php if ($block->get('options.selected')) : ?> block-selected<?php endif; ?><?php if ($block->get('options.disabled')) : ?> block-disabled<?php endif; ?><?php if ($block->get('options.closed')) : ?> block-closed<?php endif; ?>"<?php if ($block->get('options.selected')) : ?> ajax-selected<?php endif; ?> js="block" ajax-id="<?= $block->get('data.html.ajax-id') ?>" ajax-item="<?= $block->get('data.html.ajax-item') ?>" >
            <div class="block-head" js="block-head">  
                <?= $block->get('data.user_image') ?>
                <div class="inner">
                    <div class="label-list">
                        <?php require $this->path->build('Root/Style:/Templates/Blocks/Labels.phtml'); ?>
                        <span js="name"><?= $block->get('data.name') ?></span>
                    </div>
                    <span class="block-description">
                        <?= $block->get('data.user') ?>
                        <?= $block->get('data.group') ?>
                        <?= $block->get('data.reputation') ?>
                        <span ajax="title" ajax-title="<?= $this->language->get('L_CREATED') ?>">
                            <i class="fa-solid fa-clock"></i> 
                            <?= $block->get('data.date') ?>
                        </span>
                        <?php if ( $block->get('data.edited') ) : ?>
                            <span ajax="title" ajax-title="<?= $this->language->get('L_LAST_EDITED') ?>">
                                <i class="fa-solid fa-edit"></i> 
                                <?= $block->get('data.edited') ?>
                            </span>
                        <?php endif; ?>
                    </span>
                </div>
            </div>
            <?php if ( $block->get('data.image_url') ) : ?>
                <div class="block-image" style="background-image: url(<?= $block->get('data.image_url') ?>);"></div>
            <?php endif; ?>

            <?php require $this->path->build('Root/Style:/Templates/Blocks/Visualization/Block/Notices/Load.phtml'); ?>

            <div class="block-body" js="block-body">
                <div class="block-content" js="block-content"><?= $block->get('data.text') ?></div>
                <?php if ( $block->get('data.user_signature') ) : ?>
                    <div class="block-signature trumbowyg">
                        <?= $block->get('data.user_signature') ?>
                    </div>
                <?php endif; ?>
                <?php if ( $block->get('data.images') ) : ?>
                    <div class="block-images pswp-images">
                        <?php require $this->path->build('Root/Style:/Templates/Blocks/Attachments/Images.phtml'); ?>
                    </div>
                <?php endif; ?>
                <?php if ( $block->get('data.attachments') ) : ?>
                    <div class="block-attachment">
                        <?php require $this->path->build('Root/Style:/Templates/Blocks/Attachments/Files.phtml'); ?>
                    </div>
                <?php endif; ?>
                <?php if ( $block->get('data.likes') ) : ?>
                    <?php require $this->path->build('Root/Style:/Templates/Blocks/Visualization/Block/Likes.phtml'); ?>
                <?php endif; ?>
                <div js-place="likes"></div>
                <?php if ( $block->get('data.button') ) : ?>
                    <div class="block-bottom" js="block-bottom">
                        <?php $block->each('data.button', function ($button) { ?>
                            <?php if (is_string($button)) : ?>
                                <?php require $button; ?>
                            <?php else : ?>
                                <a <?php if ( $button->get('side') ) : ?>class="block-bottom-right"<?php endif; ?><?php if ( $button->get('href')) : ?>href="<?= $button->get('href') ?>"<?php endif; ?><?php if ( $button->get('ajax-action') ) : ?> ajax-action="<?= $button->get('ajax-action') ?>"<?php endif; ?>><?php if ( $button->get('icon') ) : ?><i class="<?= $button->get('icon') ?>"></i> <?php endif; ?><?= $button->get('title') ?></a>
                            <?php endif; ?>
                        <?php }); ?>
                    </div>
                <?php endif; ?>
            </div>
        </div>
    <?php }); ?>
<?php }); ?>