<div class="block-inner fw-600" js="likes">
    <span>
        <span class="like" ajax="title" ajax-title="<?= $this->language->get('L_LIKE.L_LIKE') ?>"><i class="fa-solid fa-thumbs-up"></i></span> x <span class="count" js="count"><?= $block->get('data.count_of_likes') ?></span>
    </span>
    <span class="commas" js="list">
        <?php $block->each('data.likes', function ($like) { ?>
            <?= $like->get('user_name') ?>
        <?php }); ?>
        <?php if ($block->get('data.count_of_likes') > 5) : ?>
            <a ajax-action="likes" ajax-window>... <?= $this->language->get('L_LIKE.L_MORE') ?> <?= (int)$block->get('data.count_of_likes') - 5 ?></a>
        <?php endif; ?>
    </span>
</div>