<div id="c<?= $block->get('data.profile_post_comment_id') ?>" class="block block-mini<?php if ( $block->get('options.selected') ) : ?> block-selected<?php endif; ?><?php if ( $block->get('options.closed') ) : ?> block-closed<?php endif; ?><?php if ( $block->get('options.disabled') ) : ?> block-disabled<?php endif; ?>"<?php if ( $block->get('options.selected') ) : ?> ajax-selected<?php endif; ?> js="block" ajax-id="<?= $block->get('data.html.ajax-id') ?>" ajax-item="<?= $block->get('data.html.ajax-item') ?>">
    <?php require $this->path->build('Root/Style:/Templates/Blocks/Visualization/Block/Notices/Load.phtml'); ?>
    <div class="block-body" js="block-body">
        <?= $block->get('data.user_image') ?>
        <div class="block-body-inner">
            <div class="block-head">
                <?= $block->get('data.user') ?>
                <span class="block-description">
                    <span ajax="title" ajax-title="<?= $this->language->get('L_CREATED') ?>">
                        <?= $block->get('data.date') ?>
                    </span>
                </span>
            </div>
            <div class="block-content" js="block-content">
                <?= $block->get('data.text') ?>
            </div>
            <?php if ($block->get('data.button')) : ?>
                <div class="block-bottom" js="block-bottom">
                    <?php foreach ($block->get('data.button') as $btn) : ?>
                        <?php require $btn; ?>
                    <?php endforeach; ?>
                </div>
            <?php endif; ?>
        </div>
    </div>
</div>