<div id="<?= $block->get('data.profile_post_id') ?>" class="block block-small<?php if ( $block->get('options.selected') ) : ?> block-selected<?php endif; ?><?php if ( $block->get('options.closed') ) : ?> block-closed<?php endif; ?><?php if ( $block->get('options.disabled') ) : ?> block-disabled<?php endif; ?>"<?php if ( $block->get('options.selected') ) : ?> ajax-selected<?php endif; ?> js="block" ajax-id="<?= $block->get('data.html.ajax-id') ?>" ajax-item="<?= $block->get('data.html.ajax-item') ?>">
    <div class="block-head">
        <?= $block->get('data.user_image') ?>
        <div class="inner">
            <?= $block->get('data.user') ?>
            <span class="block-description">
                <span ajax="title" ajax-title="<?= $this->language->get('L_CREATED') ?>">
                    <i class="fa-solid fa-clock"></i>
                    <?= $block->get('data.date') ?>
                </span>
            </span>
        </div>
    </div>
    <?php require $this->path->build('Root/Style:/Templates/Blocks/Visualization/Block/Notices/Load.phtml'); ?>
    <div class="block-body" js="block-body">
        <div class="block-content" js="block-content"><?= $block->get('data.text') ?></div>
        <?php if ($block->get('data.button')) : ?>
            <div class="block-bottom" js="block-bottom">
                <?php $block->each('data.button', function ($btn) { ?>
                    <?php require $btn; ?>
                <?php }); ?>
            </div>
        <?php endif; ?>
        <?php if ($block->get('body')) : ?>
            <div class="body-sub" js="block-body-sub">
                <?php $block->each('body', function ($block) { ?>
                    <?php if ($block->get('options.template')) : ?>
                        <?php require $block->get('options.template'); return; ?>
                    <?php endif; ?>
                    <?php require $this->path->build('Root/Style:/Templates/Blocks/Visualization/Block/ProfilePostComment.phtml'); ?>
                <?php }); ?>
            </div>
        <?php endif; ?>
    </div>
</div>