<div class="list-row-align">
    <?php if ( $list->get('data.button_icon') ) : ?>
        <div class="list-row-icon"><i class="<?= $list->get('data.button_icon') ?>"></i></div>
    <?php endif; ?>
    <div class="inner">
        <span class="list-title"><?= str_starts_with($list->get('data.title'), '$') ? substr($list->get('data.title') , 1) : $list->get('data.title') ?></span>
        <br>
        <span>
            <?php if ( $list->get('data.button_dropdown') == 1 ) : ?>
                <strong><?= $language->get('L_DROPDOWN.L_DROPDOWN') ?></strong>
            <?php else : ?>
                <?= $language->get('L_BUTTON.L_REFERS_TO') ?> <strong> <?= $list->get('data.button_sub_link') ?: $list->get('data.button_link') ?></strong>
            <?php endif; ?>
        </span>
    </div>
</div>