<?php if ($list->get('data.button_dropdown') == 1) : ?>
    <a class="button button-add" href="<?= $url->build('~/add/buttonsub/' . $list->get('data.button_id')) ?>"><i class="fa-solid fa-plus"></i><span><?= $language->get('L_BTN.L_ADD_BUTTON') ?></span></a>
    <a class="button button-edit" href="<?= $url->build('~/show/dropdown/' . $list->get('data.button_id')) ?>"><i class="fa-solid fa-pencil-alt"></i><span><?= $language->get('L_BTN.L_EDIT') ?></span></a>
<?php else : ?>
    <a class="button button-edit" href="<?= $url->build('~/show/button/' . $list->get('data.button_id')) ?>"><i class="fa-solid fa-pencil-alt"></i><span><?= $language->get('L_BTN.L_EDIT') ?></span></a>
<?php endif; ?>