<?php if ( $list->get('data.topic_id') ) : ?>
    <div class="inner">
        <?= $list->get('data.lastpost.user_image') ?>
    </div>
    <div class="inner">
        <div class="label-list">
            <?php require $this->path->build('Root/Style:/Templates/Blocks/Labels.phtml'); ?>
            <?= $list->get('data.lastpost.link') ?>
        </div>
        <br>
        <?= $this->language->get('L_BY') ?> <?= $list->get('data.lastpost.user') ?>
        <br>
        <span class="date"><?= $list->get('data.lastpost.date') ?></span>
    </div>
<?php else : ?>
    <span class="fw-600"><?= $this->language->get('L_POST.L_NO') ?></span>
<?php endif; ?>