<!DOCTYPE html>
<html lang="cs-cz">
    <head>
        <title>PHPCore - Internal error</title>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="description" content="Internal error" />

        <link rel="shortcut icon" type="image/x-icon" href="/Uploads/Site/PHPCore_icon_red.svg?<?= mt_rand() ?>"/>

        <link rel="preload" as="font" type="font/woff2" href="/Includes/Object/Exception/Template/Fonts/Quicksand-Light.woff2" crossorigin>
        <link rel="preload" as="font" type="font/woff2" href="/Includes/Object/Exception/Template/Fonts/Quicksand-Regular.woff2" crossorigin>
        <link rel="preload" as="font" type="font/woff2" href="/Includes/Object/Exception/Template/Fonts/Quicksand-Medium.woff2" crossorigin>
        <link rel="preload" as="font" type="font/woff2" href="/Includes/Object/Exception/Template/Fonts/Quicksand-Bold.woff2" crossorigin>

        <link rel="stylesheet" type="text/css" href="/Includes/Object/Exception/Template/Stylesheet.min.css?123455656">
        <link rel="stylesheet" type="text/css" href="/Assets/FontAwesome/css/all.min.css">
    </head>
    <body id="body" class="error">
        <div class="error">
            <div class="error-header"><img src="/Uploads/Site/PHPCore_white.svg?1s2"></div>
            <div class="error-container">
                <div class="error-body">
                    <h1>Internal error</h1>
                    <div class="error-message"><?= $error ?></div>
                </div>
            </div>
        </div>
        <?php if ($preview) : ?>
            <div class="preview">
                <div class="preview-body">
                    <span>Template: <span class="preview-name"><?= $preview ?></span></span>
                    <a ajax-action="close-preview">Close preview</a>
                </div>
            </div>
        <?php endif; ?>
        <script src="/Assets/jQuery/jQuery.min.js?<?= mt_rand() ?>"></script>
        <script src="/Assets/cAjax/cAjax.min.js?<?= mt_rand() ?>"></script>
        <script>$.cAjax({});</script>
    </body>
</html>