<?php if ($this->data->panel->get('body') or ($this->data->pagination['enabled'] ?? false) === true) : ?>
    <div class="panel panel-top" js="panel" ajax-id="<?= $this->data->panel->get('data.html.ajax-id') ?>" ajax-item="<?= $this->data->panel->get('data.html.ajax-item') ?>">
        <?php require $path->build('Root/Style:/Templates/Blocks/Pagination.phtml'); ?>
        <?php if ( $this->data->panel->get('body') ) : ?>
            <div class="panel-right">
                <?php $this->data->panel->each('body', function ($panel) { ?>
                    <?php if ( in_array($panel->get('options.type'), ['form', 'dropdown']) ) : ?>
                        <div class="dropdown dropdown-type-<?= $panel->get('options.type') ?> dropdown-name-<?= $panel->getCurrentPositionName() ?>" js="dropdown">
                            <?php if ( $panel->get('options.template.body') ) : ?>
                                <?php require $panel->get('options.template.body'); ?>
                            <?php else : ?>
                                <a>
                                    <div class="dropdown-text">
                                        <i class="<?= $panel->get('data.icon') ?>"></i>
                                        <?php if ( $panel->get('data.title') ) : ?>
                                            <span><?= $panel->get('data.title') ?></span>
                                        <?php endif; ?>
                                    </div>
                                    <div class="dropdown-arrow">
                                        <i class="fa-solid fa-caret-down"></i>
                                    </div>
                                </a>
                            <?php endif; ?>
                            <div class="dropdown-menu" js="dropdown-menu">
                                <div class="dropdown-content">
                                    <?php if ($panel->get('options.type') === 'form') : ?>
                                        <form method="post">
                                        <div class="dropdown-head"><?= $panel->get('data.form.title') ?></div>
                                    <?php endif; ?>
                                    <div class="dropdown-body">
                                        <?php $panel->each('body', function ($panel) { ?>
                                            <div class="dropdown-row">
                                                <?php if ( $panel->get('options.template.body') ) : ?>
                                                    <?php require $panel->get('options.template.body'); ?>
                                                <?php else : ?>
                                                    <a <?php if ( $panel->get('data.href') ) : ?>href="<?= $panel->get('data.href') ?>"<?php endif; ?><?php if ( $panel->get('data.ajax-action') ) : ?> ajax-action="<?= $panel->get('data.ajax-action') ?>"<?php endif; ?><?php if ( $panel->get('data.ajax-window') ) : ?> ajax-window<?php endif; ?>>
                                                        <?= $panel->get('data.title') ?>
                                                    </a>
                                                <?php endif; ?>
                                            </div>
                                        <?php }); ?>
                                    </div>
                                    <?php if ($panel->get('options.type') === 'form') : ?>
                                        <div class="dropdown-bottom">
                                            <a class="button" ajax-action="<?= $panel->get('data.form.button.ajax-action') ?>"><?= $panel->get('data.form.button.title') ?></a>
                                        </div>
                                        </form>
                                    <?php endif; ?>
                                </div>
                            </div>
                        </div>
                    <?php else : ?>
                        <?php if ( $panel->get('options.template.body') ) : ?>
                            <?php require $panel->get('options.template.body'); ?>
                        <?php else : ?>
                            <a class="button" <?php if ( $panel->get('data.href') ) : ?>href="<?= $panel->get('data.href') ?>"<?php endif; ?><?php if ( $panel->get('data.ajax-action') ) : ?> ajax-action="<?= $panel->get('data.ajax-action') ?>"<?php endif; ?><?php if ( $panel->get('data.ajax-window') ) : ?> ajax-window<?php endif; ?>><i class="<?= $panel->get('data.icon') ?>"></i><span><?= $panel->get('data.title') ?></span></a>
                        <?php endif; ?>
                    <?php endif; ?>
                <?php }); ?>
            </div>
        <?php endif; ?>
    </div>
<?php endif; ?>