<?php if ($this->data->panel['body'] ?? [] or ($this->data->pagination['enabled'] ?? false) === true) : ?>
    <div class="panel panel-top" ajax-selector="panel" ajax-process-id="<?= $this->data->panel['options']['id'] ?? '' ?>" ajax-process-type="<?= $this->data->panel['options']['type'] ?? '' ?>">
        <?php require $this->template->template('/Blocks/Pagination.phtml'); ?>
        <?php if ($this->data->panel['body'] ?? []) : ?>
            <div class="panel-right">
                <?php foreach ((array)$this->data->panel['body'] as $objName => $object) : ?>
                    <?php if ($object['options']['type'] === 'form' or $object['options']['type'] === 'dropdown') : ?>
                        <div class="dropdown dropdown-type-<?= $object['options']['type'] ?? 'default' ?> dropdown-name-<?= $objName ?>" ajax-selector="dropdown">
                            <?php if (isset($object['options']['template']['body'])) : ?>
                                <?php require $object['options']['template']['body']; ?>
                            <?php else : ?>
                                <a>
                                    <div class="dropdown-text">
                                        <i class="<?= $object['data']['icon'] ?>"></i>
                                        <?php if (isset($object['data']['title'])) : ?>
                                            <span><?= $L_BUTTON[$object['data']['title']] ?></span>
                                        <?php endif; ?>
                                    </div>
                                    <div class="dropdown-arrow">
                                        <i class="fas fa-caret-down"></i>
                                    </div>
                                </a>
                            <?php endif; ?>
                            <div class="dropdown-menu" ajax-selector="dropdown-menu">
                                <div class="dropdown-content">
                                    <?php if ($object['options']['type'] === 'form') : ?>
                                        <form method="post">
                                        <div class="dropdown-head"><?= ${$object['data']['form']['title']} ?></div>
                                    <?php endif; ?>
                                    <div class="dropdown-body">
                                        <?php foreach ((array)$object['body'] as $rowName => $row) : ?>
                                            <div class="dropdown-row">
                                                <?php if (isset($row['options']['template']['body'])) : ?>
                                                    <?php require $row['options']['template']['body']; ?>
                                                <?php else : ?>
                                                    <a <?php if ($row['data']['href'] ?? false) : ?>href="<?= $row['data']['href'] ?>"<?php endif; ?><?php if ($row['data']['ajax'] ?? false) : ?>ajax="<?= $row['data']['ajax'] ?>" ajax-process="<?= $row['data']['ajaxProcess'] ?? '/' . ucfirst($rowName) ?>"<?php endif; ?>>
                                                        <?= str_starts_with($row['data']['title'], '$') ? substr($row['data']['title'], 1) : $L_BUTTON[$row['data']['title']] ?>
                                                    </a>
                                                <?php endif; ?>
                                            </div>
                                        <?php endforeach; ?>
                                    </div>
                                    <?php if ($object['options']['type'] === 'form') : ?>
                                        <div class="dropdown-bottom">
                                            <input type="hidden" value="<?= SESSION_ID ?>" name="key">
                                            <input type="submit" name="<?= $object['data']['form']['button']['name'] ?>" class="button" value="<?= $L_BUTTON[$object['data']['form']['button']['value']] ?>">
                                        </div>
                                        </form>
                                    <?php endif; ?>
                                </div>
                            </div>
                        </div>
                    <?php else : ?>
                        <?php if (isset($object['options']['template']['body'])) : ?>
                            <?php require $object['options']['template']['body']; ?>
                        <?php else : ?>
                            <a class="button" href="<?= $this->url->build($object['data']['href']) ?>"><i class="<?= $object['data']['icon'] ?>"></i><span><?= $L_BUTTON[$object['data']['title']] ?></span></a>
                        <?php endif; ?>
                    <?php endif; ?>
                <?php endforeach; ?>
            </div>
        <?php endif; ?>
    </div>
<?php endif; ?>